### ISSUE TITLE
Formatting issue on libretranslate.com

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#101]
![image](https://user-images.githubusercontent.com/13067016/121783436-40476e00-cb74-11eb-9aab-5b992f860399.png)

**Comment by pierotofy** [comment]
Seems to be a cache issue; if you force refresh the page it should load correctly. I've also pushed https://github.com/LibreTranslate/LibreTranslate/commit/9dfd4dda0937621cc7c6323199cd8858d47b2e8d to invalidate the cache.
