### ISSUE TITLE
Android/iOS app 

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#102]
We could pretty easily make a LibreTranslate app by packaging the web app using tools like PhoneGap.

**Comment by hellojaccc** [comment]
PWA also will be great

**Comment by MXC48** [comment]
then there is a fairly nice application as customer on android a free translate
which is called freetranslate
I am French and I write this answer with this application:-)
the link to download it:
https://fossdroid.com/a/libretranslator.html
