### ISSUE TITLE
vscode extension default url for libretranslate

### ISSUE THREAD

**Issue by farfromrefug** [LibreTranslate/LibreTranslate#106]
I wrote to add support for libretranslate in i18n-ally https://github.com/lokalise/i18n-ally/pull/607#pullrequestreview-694621810.
They asked me to change the default URL to `https://libretranslate.com/translate`. Is that ok with you?
Maybe there is a rate limit there. If it was me i would stick to `http://localhost:5000` but i prefer to ask

**Comment by pierotofy** [comment]
Thanks for checking! :pray: 

It would be better if there was no default at all. (e.g., always require the developer to specify a host for the service). 

If you absolutely need a default, I think localhost is a better one. Note you need an API key to use libretranslate.com anyway.
