### ISSUE TITLE
How to override few translation ?

### ISSUE THREAD

**Issue by Akshay-Hegde** [LibreTranslate/LibreTranslate#108]
- I want to manually override few translations (some paragraphs in which grammar needs to be corrected manually) in translated language.

What's the procedure ? 
Also is there any online documentation available to refer ?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by Akshay-Hegde** [comment]
Thanks ! I followed as you suggested
