### ISSUE TITLE
build offline option for specific language 

### ISSUE THREAD

**Issue by Akshay-Hegde** [LibreTranslate/LibreTranslate#111]
```
docker build  with_models=true -t libretranslate .
```
1. Probably in future commit if any args to specify required model only then data can be saved as offline build image is around ~ 11GB.

       Example: en,fr,es
2. Option to run as non root user, may be something like `USER 1001`

Something like below

```
ARG with_models=false
ARG models=

RUN if [ "$with_models" = "true" ]; then  \
        # install only the dependencies first
        pip install -e .;  \
        # initialize the language models
         if [ ! -z "$models" ]; then \
                  ./install_models.py "$models";   \
         else \
                  ./install_models.py;  \
         fi
     fi
```
and then build 

```
docker build  with_models=true models="en,es,fr" -t libretranslate .
```

**Comment by pierotofy** [comment]
That would be a cool addition! Interested in contributing a PR @Akshay-Hegde ?

**Comment by Akshay-Hegde** [comment]
@pierotofy probably if we can have provision to pass arguments to `install_models.py` docker image size can be smaller.

**Comment by setokesan** [comment]
Hi, I modified the code and I would like to push my proposal, but I don't know how to proceed. Do I need to be a contributor?

**Comment by pierotofy** [comment]
Nop, anyone can open a pull request; https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by setokesan** [comment]
I added a PR at #235 
Example of command is 
`docker build -t libretranslate:latest --build-args models=en,jp .`

Cheers!

**Comment by ricardoborges** [comment]
I tried to run with "docker build -t libretranslate:latest --build-args models=en,pt ." and it's not working

 unknown flag: --build-args

any thoughts?

**Comment by ricardoborges** [comment]
nevermind, I copy and past the command in plural --build-args  but it's singular --build-arg.

Great feature! That should be in the docs! thanks!

**Comment by pierotofy** [comment]
> That should be in the docs!  

Help us improve them? :pray:
