### ISSUE TITLE
Feature request: dockerhub documentation and env

### ISSUE THREAD

**Issue by euberdeveloper** [LibreTranslate/LibreTranslate#113]
On the dockerhub image, it would be beautiful to have a README or something with documentation

In addition, it would be beautiful to have (if there are not yet) the options as ENV variables, so that in a docker compose you can just put the envs

**Comment by pierotofy** [comment]
Excellent ideas! Would you be interested in contributing a PR?

**Comment by euberdeveloper** [comment]
I am only a user, so I have not read the code, but if I find the time I could do one

**Comment by euberdeveloper** [comment]
@pierotofy I have just made a pull request. I am not sure if it is ok, a revision should be done. As writen in the pull request's description, it adds the possibiliy of using env. vars, with higher priority of default values and lower priority than passed args

**Comment by PJ-Finlay** [comment]
It looks like it should already be pulling the README.md file according to this answer:

https://stackoverflow.com/questions/34710513/how-can-i-update-full-description-on-docker-hub-automatically

**Comment by euberdeveloper** [comment]
Yes, if you build and publish by your cloned repo I think

But here it does not appear https://hub.docker.com/r/libretranslate/libretranslate

**Comment by pierotofy** [comment]
I fixed the docker hub page, and the README from GitHub should now sync with it. Thanks for the report (and the PR for the env stuff). :pray:
