### ISSUE TITLE
Whats about WASM and integration with Linguist?

### ISSUE THREAD

**Issue by vitonsky** [LibreTranslate/LibreTranslate#120]
Hi, i work on browser extension "Linguist" for translate pages and other text, you can see it here https://github.com/translate-tools/linguist

Right now Linguist use translate services, but i want to make absolutely autonomic mode for improve privacy and allow translate text offline. For this purpose i need standalone translator with high quality and supporting many languages and your project looks that. But i can't force users install LibreTranslate locally, because it too hard for common user and is not user friendly, but browser extension must be.

So i search an project which can support [WebAssembly](https://webassembly.org/) and work fast.

- Is require this program an internet connection in any time for working?
- How many disk space require this program for keep dictionaries or AI models?
- Have your project something bindings which can make problems for porting it on WASM?

If not, is have you these plans or can you give me help to make port?

I have big plans on Linguist and its architecture allow use any module for translate text, would excellent if you ready to interop

**Comment by pierotofy** [comment]
I personally have no plans to port LibreTranslate to 100% web, but if somebody did figure out how to do it, I'd welcome a pull request!

**Comment by vitonsky** [comment]
What about my sub-questions? This matter to understand ability to porting

**Comment by PJ-Finlay** [comment]
This would probably be difficult but would require compiling CTranslate2 for WebAssembly (@guillaumekln). You would probably then need to either run Python in WebAssembly for Argos Translate or use CTranslate2 alone.

**Comment by pierotofy** [comment]
I'm going to close this (PR still welcome of course).
