### ISSUE TITLE
special characters breaks translation

### ISSUE THREAD

**Issue by farfromrefug** [LibreTranslate/LibreTranslate#123]
I use libretranslate to translate app localized messages like `Hello %1$s, good to see you again!`
This will break the translation and only "hello" will be translated.
It would be great if you could make it work like it does with google translate for example.
I think the translation is broken into 2 `Hello` and `, good to see you again!` and then merged again after translation

**Comment by farfromrefug** [comment]
Just found out another example where it fails
translating this to english:
```
Je souhaite rendre <span style=\"color:%2$s;\">%1$s</span> dabbas à mon commerçant
```
Gave this:
```
I wish to make <span style=\"color:%2$s;\" rise%1$s</span raised dabbas to my merchant
```

In this case it is not "broken" and translate only a part but there is one issue remaining in this case. `>` is translated to `rise` and the other one to `raised`. Nice :D but not wanted

**Comment by dingedi** [comment]
this seems fixed from html support.
