### ISSUE TITLE
Submit translations

### ISSUE THREAD

**Issue by ovari** [LibreTranslate/LibreTranslate#130]
How can translations be provided to improve the LibreTranslate application?

| English | magyar (Hungarian) incorrect | magyar (Hungarian) correct |
|----|----|----|
| bootstrap | bootstrap | rendszerindítás |
| queue | sor | várakozási sor |
| script | szkript | parancsfájl |
| server | szerver | kiszolgáló |
| What’s the time? | Mennyi az idő? | Hany óra? |

Translations could be added from:
1. [Angol-magyar informatikai szótár](https://regi.tankonyvtar.hu/en/tartalom/tkt/angol-magyar/adatok.html). [PDF version](https://regi.tankonyvtar.hu/en/tartalom/tkt/angol-magyar/angol-magyar.pdf)
2. [SZTAKI dictionary](https://szotar.sztaki.hu/en)

What do you think?

Thank you

**Comment by pierotofy** [comment]
https://github.com/argosopentech/argos-parallel-corpus
