### ISSUE TITLE
Docker deploy stop working after last updates

### ISSUE THREAD

**Issue by ZEROF** [LibreTranslate/LibreTranslate#131]
Hello,

I saw that you pushed 2 or 3 new languages (and that is great), but that break docker deployment:

Downloading French -> English (1.0) ...
Downloading German -> English (1.0) ...
Downloading Hindi -> English (1.1) ...
Cannot update models (normal if you're offline): name 'Error' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 107, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 96, in create_app
    raise AttributeError(
AttributeError: en as frontend source language is not supported.

Used docker run command:

 docker run -ti -d -p 5000:5000 libretranslate/libretranslate --frontend-language-source en --frontend-language-target fr

**Comment by PJ-Finlay** [comment]
Can someone confirm? It appears to work in my tests

**Comment by ZEROF** [comment]
Small update. I tried to build image with modules using: 

docker build -t libretranslate/libretranslate --build-arg with_models=true .

Error: https://paste.lugons.org/?59accdeb8e5894d9#DgTmqZeExbTCBzNUbTxqmxsCiDkuswBW286u2McTz1Uv

That is not working either.

**Comment by PJ-Finlay** [comment]
Should be fixed, I fixed a typo in the hindi model name while I was adding Hungarian not realizing the model name had a typo in the CDN.

https://github.com/argosopentech/argospm-index/commit/c32662378d328e114aee08926dbe777f7d5c9888#diff-7aebb122a6ea8a2749d60cb05b7e103c9eae6e2e85e48d2d6cd9e20b63013975L286
