### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by GamearooCodes** [LibreTranslate/LibreTranslate#132]
https://libretranslate.com/translate reports that i need a api key 

![image](https://user-images.githubusercontent.com/50187502/132284953-7c5d5801-03b2-46a5-8f72-668e1b15dc74.png)

**Comment by pierotofy** [comment]
Correct; the API server on libretranslate.com requires one.

See https://github.com/LibreTranslate/LibreTranslate#mirrors for alternatives, or support the project by signing up for a subscription and get an API key? :pray: 

https://buy.stripe.com/28obLvdgGcIE5AQfYY
