### ISSUE TITLE
Bug now fixed in Swedish model on package index

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#133]
There was a typo in the Swedish model name that led to an error when you tried to translate Swedish to English on https://libretranslate.com, should be fixed now.

- https://github.com/argosopentech/argospm-index/commit/195eee0f7dad0bb1af97ec356fce19fbd062db26

**Comment by pierotofy** [comment]
Can confirm this is fixed, thanks!
