### ISSUE TITLE
Add a parameter in the API to translate html

### ISSUE THREAD

**Issue by dingedi** [LibreTranslate/LibreTranslate#134]
Maybe you could add a parameter (format: text or html) in the API to allow translating html?

Thanks to [https://github.com/argosopentech/translate-html](argosopentech/translate-html)

I can do a pull request if interested.

**Comment by PJ-Finlay** [comment]
https://github.com/LibreTranslate/LibreTranslate/issues/55

**Comment by pierotofy** [comment]
A pull request would be amazing! A `format` parameter would work well.

**Comment by dingedi** [comment]
#135

**Comment by pierotofy** [comment]
Done! :+1:
