### ISSUE TITLE
German->English response returns only partial of text

### ISSUE THREAD

**Issue by caudurodev** [LibreTranslate/LibreTranslate#136]
You can test this on any installation via the interface or API. By adding this text to translate from German to English,  you will receive only a portion back:

```Es war deshalb fast schon ein bisschen drollig, am Montagabend im deutschen Fernsehen zu beobachten, wie schwer der Umgang mit einer Figur wie Baerbock offenbar fällt: Während die beiden Interviewer bei Pro Sieben zärtlich mit der Grünen-Kandidatin scherzten und am Ende tatsächlich applaudierten, attestierte ihr Claus Kleber beinahe väterlich, "wie ein alter Profi" zu agieren, was lustig ist, denn Annalena Baerbock sitzt immerhin seit acht Jahren im Bundestag und ist seit drei Jahren Parteivorsitzende. ```

this returns for me: 

``` it was therefore almost a bit drolly to watch on Monday night in German television, how difficult the change with a figure like baerbock seems: while the two interviewers at pro seven ceremoniously joked with the Green Candidate and at the end actually applauded, their claus adhesive was almost paternally, "how an old profi" was always sitting on```

It is missing the last parts of the text. 

I do not have limits to chars set or any other restrictions on my installation. Would this issue be related to the actual translation or could it be some special character that has been inputted? Or maybe something else I've overlooked?

I can reproduce the behavior in libretranslate.de as well.

Are there any configurations that could make this behaviour change?

**Comment by dingedi** [comment]
I tried directly in cli with argos-translate and there is the same problem.
This problem is more related to models and argos-translate, you can open an issue directly on the [argostranslate github](https://github.com/argosopentech/argos-translate)
