### ISSUE TITLE
PyPI package is broken on archlinux because of old pyicu dependecy

### ISSUE THREAD

**Issue by eugenemw** [LibreTranslate/LibreTranslate#138]
New release to include #109 would solve the problem

**Comment by pierotofy** [comment]
Thanks for the report! I just published a new release with the latest changes. :+1:

**Comment by eugenemw** [comment]
Broken again with `pyicu==2.7 `
now `archlinux` needs `pyicu>=2.8` which means `libicui18n.so.70`
