### ISSUE TITLE
offline mode since last update

### ISSUE THREAD

**Issue by Dominion0815** [LibreTranslate/LibreTranslate#139]
Hi,

I'm missing --offline after last update. Is it possible to start docker container without external CDN urls?

Regards
Dominion

**Comment by pierotofy** [comment]
Yes! You do not need the offline flag anymore (all files are already included in the container, no CDN).

**Comment by Dominion0815** [comment]
ok but I still have cdn urls:


	```
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
	<!-- Compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/themes/prism.min.css" rel="stylesheet" />
```

**Comment by pierotofy** [comment]
Try to clear your cache and make sure you're running the latest version?

https://github.com/LibreTranslate/LibreTranslate/blob/main/app/templates/index.html#L19

**Comment by Dominion0815** [comment]
solved. I didn't use the new index.html template ;)
