### ISSUE TITLE
Add a "Feeback" option to Improve Translations

### ISSUE THREAD

**Issue by marreromarco** [LibreTranslate/LibreTranslate#140]
**Would it be possible to add an “Optional” Feedback to improve the quality of translations ?**

**Comment by pierotofy** [comment]
Sure! Would you be interested in contributing to such functionality?

**Comment by marreromarco** [comment]
> Sure! Would you be interested in contributing to such functionality?

I would like to contribute as much as possible with LibreTranslate. I could proofread/correct English to Spanish sentences to improve the quality of the service. 

As I am not a technical user, I am not able to contribute with code, but manual correction of translations might be valuable too.

For example, Google Translate has a “feedback” option:

![image](https://user-images.githubusercontent.com/58692066/134070687-ea9120b9-b941-43df-970f-c0f074720205.png)
![image](https://user-images.githubusercontent.com/58692066/134071068-bdfdceb7-0787-45a1-bc72-3524dc291e10.png)

DeepL also has a feedback mechanism:
![image](https://user-images.githubusercontent.com/58692066/134071068-bdfdceb7-0787-45a1-bc72-3524dc291e10.png)

I believe that both kinds of feedback could be added. The difficult part would be to integrate the data from feedback into the actual algorithms/coding.

**If there is a way to cooperate as a part-time language editor, I would be glad to participate.**

**Comment by pierotofy** [comment]
You can now submit suggestions via the web UI #151 !
