### ISSUE TITLE
English -> Turkish translation results in inappropriate websites ?

### ISSUE THREAD

**Issue by CaptainCaptcha** [LibreTranslate/LibreTranslate#141]
Hi, I am really confused right now. If you enter meaningless words like random characters, English to Turkish translation has some really weirds results. 

Here they are :

![2021-09-23 01_32_39-Window](https://user-images.githubusercontent.com/86262252/134431244-e251ac4a-784e-4abf-9cc7-59f8d698f35a.png)
![2021-09-23 01_32_26-Window](https://user-images.githubusercontent.com/86262252/134431247-616d62c6-e6be-4160-b6a1-3665e683ff56.png)
![2021-09-23 01_31_58-](https://user-images.githubusercontent.com/86262252/134431248-eaff20ba-73b3-40a4-b156-9360d1db8c55.png)
![2021-09-23 01_31_14-Window](https://user-images.githubusercontent.com/86262252/134431249-e76b6c2e-cb3f-430b-905a-6f1c48c57e37.png)
![2021-09-23 01_30_42-Window](https://user-images.githubusercontent.com/86262252/134431252-aeae58ae-585b-4694-a3f5-1a1317e49c00.png)

I did not manipulate the website in any ways. You can try by going to https://libretranslate.com/ and selecting English -> Turkish then typing things I wrote above. I was about to use this on a project of mine but I luckily saw this. How is this even possible ? When I write something meaningless like "aaaa", it should output as "aaaa" not "xHamster". I'm both angry and hilarious right now. This is ridiculous. Please fix this and ban contributors of these translations.

**Comment by pierotofy** [comment]
Ah, interesting! It might have to do with the quality of the training data used for the Turkish model.

**Comment by CaptainCaptcha** [comment]
@pierotofy Yeah, looks like some idiots trolled the data for Turkish model. You might want to use another one. Thanks for the response.

**Comment by PJ-Finlay** [comment]
Well wasn't expecting this...

```
argosopentech@dev:~/turkish$ grep -n -i xhampster *.en
CCAligned.en-tr.en:5169773:Hentai Xhampster 
CCAligned.en-tr.en:5633651:xHampster 
CCAligned.en-tr.en:5953336:Xhampster 
CCAligned.en-tr.en:6462245:www xhampster 
CCAligned.en-tr.en:6890391:86 xHampster 
CCAligned.en-tr.en:7864361:86 xHampster 
CCAligned.en-tr.en:8557318:mature anal xhampster 
CCAligned.en-tr.en:8778707:86 xHampster 
CCAligned.en-tr.en:9356316:64 xHampster 
CCAligned.en-tr.en:9828279:xhampster 
CCAligned.en-tr.en:13434664:sallow skirt - unforeseen synopsis be proper of xhampster 
```

I don't think it was malicious though. It looks like the Turkish data for CCAligned which is scraped from the internet automatically. There is a lot of porn on the internet so probably not too surprising that this ended up in the data.

We could add "xhampster" to list of filtered phrases but until there's a more robust way of dealing with profanity probably not worth it. Training separate models without profanity is possible, but in some situations we may want to correctly translate it too. Generating profanity when it isn't given as an input definitely isn't ideal though.

**Comment by PJ-Finlay** [comment]
Looking more there's actually quite a bit of profanity in the data. CCAligned seems to have much more than WikiMatrix and some other datasets.

We already filter some words out before training and could add more if this becomes a problem.

**Comment by CaptainCaptcha** [comment]
@PJ-Finlay That's interesting, thanks for your research.

**Comment by Thewisem** [comment]
Didn't knos libretranslate could become a search for which website of porn I want to watch lol
