### ISSUE TITLE
Allow to translate the same language?

### ISSUE THREAD

**Issue by dingedi** [LibreTranslate/LibreTranslate#143]
I don't know if this is a choice or a bug but shouldn't we prevent translating the same language?

![image](https://user-images.githubusercontent.com/64697405/134538795-e4253c34-de58-48df-a445-38116a6f4a34.png)

**Comment by pierotofy** [comment]
Google Translate works the same way, so I'd say why not?

**Comment by dingedi** [comment]
for me Google translate automatically changes the source language if I try to translate in the same language

**Comment by dingedi** [comment]
Maybe it should be replaced by the previous language like Google Translate does
Or put the source language in automatic detection like DeepL
Or leave it like that

**Comment by pierotofy** [comment]
I'm open to changes; feel free to open a PR for this. :pray:

**Comment by dingedi** [comment]
As soon as I have time I'm thinking of doing a PR with a system like Google Translate does as the automatic detection function is still experimental
