### ISSUE TITLE
HTML translation losing formatting

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#144]
```
- "<p>hello</p>"       EN -> FR: "pulphello vécu/p"   (bug)
- "<p>bonjour</p>"   FR -> EN: "<p>Hello.</p>"      (good)
- "<p>hello</p>"       FR -> EN: "<p>hello.</p>"       (good, no translation needed)
```

I think this is being causes by [transliterating the HTML before translating](https://github.com/LibreTranslate/LibreTranslate/blob/0a7c8ebae975586ad9e500b0db9c9cc85bfc5984/app/app.py#L423).

- https://github.com/argosopentech/argos-translate/issues/190

**Comment by pierotofy** [comment]
Spot on :+1:

**Comment by pierotofy** [comment]
![image](https://user-images.githubusercontent.com/1951843/134701956-b7eb44ed-49bc-4c01-8550-4911edf5dff3.png)
