### ISSUE TITLE
[question] LibreTranslate Firefox search engine?

### ISSUE THREAD

**Issue by Uhter** [LibreTranslate/LibreTranslate#146]
Hi everyone.

I'm a newbie. Can we add a LibreTranslate search engine to Firefox?

I tried different search URL like:
`https://libretranslate.com/search?q=%s`
or
`https://libretranslate.com/%s`

Do you know a way to add LibreTranslate search engine with a keyword?

**Comment by Uhter** [comment]
> You're trying to use your Firefox search bar to do a translation?

Yes I do.

> This is something that could be added to a [Firefox extension](https://github.com/LibreTranslate/LibreTranslate/issues/55).

It's interesting but I think that an addon will always be heavier.

**Comment by dingedi** [comment]
I don't think this is possible without creating an extension

**Comment by Uhter** [comment]
I understand ¯\_(ツ)_/¯
Thanks to all.
