### ISSUE TITLE
WARNING:polyglot.detect.base:Detector is not able to detect the language reliably.

### ISSUE THREAD

**Issue by open-antux** [LibreTranslate/LibreTranslate#148]
Today I pulled the docker image (LibreTranslate version: 1.2) on my machine, but when I try to auto detect a language the response is:
```json
[
  {
    "confidence": 0,
    "language": "en"
  }
]
```
If I attach the docker container it gives me this error `WARNING:polyglot.detect.base:Detector is not able to detect the language reliably.`

**Comment by PJ-Finlay** [comment]
Is it ever able to detect the language?

**Comment by open-antux** [comment]
After a couple of container restarting, the language auto detect seems to work. The warning remain but the response is correct now

**Comment by jasperan** [comment]
So, you did nothing but to restart a couple of times? @open-antux 

That's weird that it works for you. I have the same issue, not able to properly detect language.

**Comment by open-antux** [comment]
From what you remember yes, I hadn't made any changes

**Comment by jasperan** [comment]
Then I'll have to reply on langdetect's Python library for language detection instead

**Comment by BiggA94** [comment]
I can reproduce this bug.

This seems to be a Problem with the Docker container itself.
On Startup, the container downloads the language files.
If there isn't a separate volume mount, to save the language files outside of the folder, the container does reload the language files on every startup. (So far so good)

After the language files are loaded, the server seems to require a restart (which is not done inside the docker container).

Workaround would be, to use a volume mount, where the language files are stored and restart the server after the download.

for example, use the following docker compose file:
``` docker-compose
version: "3"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    stdin_open: true
    tty: true
    volumes:
      - polyglot_data:/root/.local/share/LibreTranslate/polyglot_data
    ports:
      - 5000:5000
    environment:
      - LT_SUGGESTIONS=true
      - LT_FRONTEND_LANGUAGE_TARGET=de
      - LT_LOAD_ONLY=de,fr,en

volumes:
  polyglot_data:

```

The problem, I have with this is, that there is no "download job" that simply downloads the language and exits afterwards.
(This would be very handy for a init container for Kubernetes).

So my Suggestion for the Docker Image:
* ability to start the image with a new command that only downloads (or updates) the needed files and exits
* update usage of the docker image in the Readme
