### ISSUE TITLE
Publish with_models=true container to DockerHub

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#155]
Could we publish a [LibreTranslate container image with models included](https://github.com/LibreTranslate/LibreTranslate#build-with-docker) on DockerHub? It would make integrating with different cloud providers and CI tools easier.

- https://github.com/LibreTranslate/LibreTranslate/pull/59

**Comment by pierotofy** [comment]
All for it. Maybe with a different tag (e.g. `libretranslate/libretranslate:models`) ?
