### ISSUE TITLE
Only download specific language models?

### ISSUE THREAD

**Issue by takattowo** [LibreTranslate/LibreTranslate#158]
Well first I am really sorry because i don't code python. But i really like this project as it helps me a lot. One thing i don't like is i had to download 42 language models everything i run it and usually took up to 2 hours to finish (my internet is bad).
So i would like to know if i can modify it so it will only download one or some specific models? Like Chinese > English and then run the server.

**Comment by matthieu-labas** [comment]
Seems to have moved here: https://community.libretranslate.com/t/only-download-specific-language-models/188
