### ISSUE TITLE
Login, Sitemap, Meme it

### ISSUE THREAD

**Issue by Linerly** [LibreTranslate/LibreTranslate#161]
!["Login"](https://user-images.githubusercontent.com/47475676/139438078-94e17eb4-99aa-44ac-b7de-0df883f3a2d5.png) (one word, even random ones)

!["Sitemap"](https://user-images.githubusercontent.com/47475676/139439247-e545ac6b-d26c-4458-870f-518695f3eaca.png) (one or two words, could be random)

!["... Meme it"](https://user-images.githubusercontent.com/47475676/139439392-a9abee18-3288-4c2b-ab72-4d0cfd156d92.png) (mostly happens when I translate a nonsense sentence)

!["Home"](https://user-images.githubusercontent.com/47475676/166879769-a849eee3-241b-4fff-819e-239ee682fa94.png)
(not sure but this happens randomly)

**Comment by dingedi** [comment]
I think its an argos translate issue. maybe the model ? @PJ-Finlay

**Comment by PJ-Finlay** [comment]
Sometimes the model has strange outputs for difficult to understand reasons. The main way to improve this is to have data similar to what is being translated and train more powerful networks.
