### ISSUE TITLE
Translating to multiple languages, then back to English

### ISSUE THREAD

**Issue by Linerly** [LibreTranslate/LibreTranslate#163]
...sometimes it's hilarious when I translate to random languages available in LibreTranslate:
> Error of communication is human. there are many different platforms.
What do we do?
Also said there is public service for a sophisticated hunter and turkey. See you again!

> there is no genetic types available with software.
                                                    
bhabhi aliti
in any case, love on your father or resident cannot be provided.
other procedures are illegal, murder and efficiency.
advocacy and other crude oil, throat or treatment of pension or punishment
software or other differences

...and "Let's twist-translate texts shall we? ...with the wackiness of LibreTranslate" got turned into "how if he sends information?"

---

Anyway, here's what I have:

Languages: English -> Vietnamese -> Hindi -> German -> Korean -> Indonesian -> Arabic -> Turkish -> English

First one:
> Hi, hello, I like breakfast. I’m talking about, for example, eggs Benedict with smoked salmon, and then an omelette, and then an apple, and maybe a glass of prosecco, and some mint tea, and, as a reward, I’d like to eat a delicious sandwich that is just the right amount of buttery, but still the perfect amount of fresh. But this is not your typical recipe for eating breakfast.

LibreTranslate:
> Hello, like breakfast, for example, salmon and smoke eggs -- pendecaine, omlet, apples, a glass show, a little merote and gift, I want to eat delicious sandwiches, only the correct amount of butter, but still freshly accurate amount. but not a special prescription for this breakfast.

Google Translate:
> Hello, I love breakfast. Eggs Benedict with smoked salmon, omelette, apple and maybe a glass of wine and mint tea as a bonus. Just the right amount of delicious sandwiches. Butter, but fresh enough. But this is no ordinary breakfast recipe.

for some reason LibreTranslate puts an extra character " -- ", the languages aren't too much so that's why it's weird but fine

---

Second one, shorter, with the same languages:
> Oh, need to wake up. Oh, you're still asleep.

LibreTranslate:
> You must come. she sleep, mymi.

Google Translate:
> Oh, you have to wake up. Oh, you're still sleeping.

No surprise that Google Translate is getting better nowadays

**Comment by Linerly** [comment]
Here are some more things that I "twist-translated":
> How to get there? No information requested by the bank, e-mail, message information, appeal and Uzbek.

> You can read and modify your site quickly. You can get on the phone for reading and reading.

> Every year, young and dreamed. Very good for my network to make paint, aruna, arizona, best film, best picture of children, clean, white, pasted and white bridge. As a result, flower coach, arizonad, arizonad, polish, all kinds will be covered, city and we please everything anonymous. Who? Waists are words prepared by gray and black feet and I will enjoy the opportunity and black support, all the ends of the... never remember his head and jewelry, the name of sapon. tell you, but you can say. Ready, warm, voice and belief and now there will be no waves of girls.
Home

(there's also the "Home" as well, if I remember correctly it was translated from Turkish then finally back to English)

**Comment by dingedi** [comment]
This problem is more related to models and argos-translate, you can open an issue directly on the [argostranslate github](https://github.com/argosopentech/argos-translate)
