### ISSUE TITLE
Translating repeating words/characters gives weird results

### ISSUE THREAD

**Issue by Linerly** [LibreTranslate/LibreTranslate#168]
!["ko re" 1](https://user-images.githubusercontent.com/47475676/140476697-f044a7ea-3796-44a9-a760-c920de06f35d.png)
!["ko re" 2](https://user-images.githubusercontent.com/47475676/140476796-d153232d-064b-438f-ba52-9a1d62c71ccb.png)
!["apa"](https://user-images.githubusercontent.com/47475676/140476896-67aae02e-71f5-41cd-a4a6-6e25ab78ed31.png)
!["que"](https://user-images.githubusercontent.com/47475676/140476939-d75e3454-e26d-499d-8154-f7aadd0add44.png)
!["y7"](https://user-images.githubusercontent.com/47475676/140476990-37d06c1a-5cc1-48c3-97a0-39486de84b0e.png)
!["ui" 1](https://user-images.githubusercontent.com/47475676/140477049-90e40046-949f-48a9-ae32-1c4e138c37fb.png)
!["ui" 2](https://user-images.githubusercontent.com/47475676/140477435-79831bcd-8264-426f-b6c1-56b12b374f07.png)
!["cy"](https://user-images.githubusercontent.com/47475676/140477302-07acd3f7-7730-447d-bd31-b5b03455d5dd.png)
!["???????? ..."](https://user-images.githubusercontent.com/47475676/140477523-a7b2340b-4e49-4799-b94d-98f41a1e72ce.png)

...yeah

**Comment by dingedi** [comment]
Is related to #167 ? @PJ-Finlay

**Comment by PJ-Finlay** [comment]
@dingedi likely. In this case since there's an unusual input it's also possible the sentence boundary detection system is acting strangely. This can be checked with `export DEBUG=1`.

**Comment by thomas-mc-work** [comment]
Is that really an issue of LibreTranslate or rather of https://github.com/argosopentech/argos-translate?

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/212
