### ISSUE TITLE
[Bug] Bad spanish / english translation

### ISSUE THREAD

**Issue by wuniversales** [LibreTranslate/LibreTranslate#17]
### Capture of errors
![image](https://user-images.githubusercontent.com/48658161/104960164-fc40aa80-59d3-11eb-9864-6c2573d9c1e6.png)
### However, entering one " , " translates correctly.
![image](https://user-images.githubusercontent.com/48658161/104960301-3f028280-59d4-11eb-98d4-8c973fc383d1.png)
### Auto-detect does not detect the language.
![image](https://user-images.githubusercontent.com/48658161/104960329-50e42580-59d4-11eb-86d6-a9a2b77c4513.png)
Greetings

**Comment by PJ-Finlay** [comment]
This may be related to [this](https://github.com/argosopentech/argos-translate/issues/17) Argos Translate issue.
