### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by thomas-mc-work** [LibreTranslate/LibreTranslate#170]
Currently the Docker image is based on `python:3.8` which finally points to `3.8.12-bullseye`. There are also `3.8-slim` and `3.8-alpine`. Here is a comparison of these base image sizes:

- `3.8.12-bullseye`: 331 MB
- `3.8-slim`: 44 MB
- `3.8-alpine`: 16 MB

Is there a specific reason to go with the largest option `3.8.12-bullseye`? If not, then the switch to `3.8-slim` should be seamless. The switch to `3.8-alpine` would require some effort. But it shouldn't be too much.

Would you generally be open to a switch? From my point of view there shouldn't be any disadvantages.

**Comment by pierotofy** [comment]
I'm up for a switch if it reduces the image size. :+1:
