### ISSUE TITLE
Docker: 1 GB of possible useless cache data

### ISSUE THREAD

**Issue by thomas-mc-work** [LibreTranslate/LibreTranslate#171]
The current Docker image has a size of 4.36 GB. Inside I found a folder worth about 1 GB:

`/root/.cache/pip`

This is probably a relict from the installation process. Wouldn't it be possible to provide the image without that data?

**Comment by thomas-mc-work** [comment]
I've tested it and it worked!

    FROM libretranslate/libretranslate:latest

    RUN rm -rf /root/.cache/pip

**Comment by pierotofy** [comment]
Nice! Would you be able to open a PR and modify our dockerfile? :pray:  I don't think it has been optimized much.

**Comment by thomas-mc-work** [comment]
I'll give it a shot.

**Comment by thomas-mc-work** [comment]
Solved by #173
