### ISSUE TITLE
Docker Hub: provide proper tags

### ISSUE THREAD

**Issue by thomas-mc-work** [LibreTranslate/LibreTranslate#174]
Regarding images on Docker Hub:

<https://hub.docker.com/r/libretranslate/libretranslate/tags>

Currently, there are only two floating tags: `main` and `latest`. For reproducibility, it would be great to reflect [the version tags of this repository](https://github.com/LibreTranslate/LibreTranslate/tags).

**Comment by feliskio** [comment]
What could a solution to this look like? @pierotofy 
One idea would be to trigger an Action upon release and pushes an image to Docker Hub with the release tag as the image tag. This should be fairly simple to implement and I could create a PR for it.
Older image versions would probably have to be added manually.

**Comment by pierotofy** [comment]
Yeah a PR would be most welcome :pray: 

The only issue is that docker hub will automatically remove images that don't get pulled after a while, so some releases might disappear from docker hub randomly over time.

**Comment by feliskio** [comment]
What if there is never an image that doesn't get pulled? 😉
It would possible to set up an action with cron trigger that automatically pulls all release images for example once a week. Although I am not sure if that's against their TOS.

I'll open a PR soon.

**Comment by feliskio** [comment]
For whatever reason the script seems to silently fail without error message. At least I can't find an image on neither Docker Hub nor GitHub packages. Do you have access to further information, @pierotofy?

**Comment by pierotofy** [comment]
I think we had an incorrect value for the docker hub username secret. I should have fixed it with https://github.com/LibreTranslate/LibreTranslate/commit/39c6cd6e8a5f0bdd8707ae67a52e95e2d0c4b4bd

**Comment by pierotofy** [comment]
This was resolved with #233
