### ISSUE TITLE
The website's api limitation is way too low.

### ISSUE THREAD

**Issue by Dinir** [LibreTranslate/LibreTranslate#181]
I tried to type a short sentence '근데 걔는 과자 좋아해요?' in the textarea and I got an api limit. It says "30 per 1 minute" so I guess I spent more than 30 keystrokes to write the sentence. I tried to do it a couple more times and now I get "Too many request limits violations".

This is just not right. I was trying to see how the translation looks for the first time.

**Comment by pierotofy** [comment]
Hey @Dinir :hand: sorry about that; try copying/pasting the text all at once to avoid this issue if you're just testing.

Alternatively, run your own instance (which will have no limits).

**Comment by lua-rocks** [comment]
@pierotofy Could you please make Ctrl+Enter text send instead of sending each letter?

**Comment by pierotofy** [comment]
I'd welcome a pull request that changes the current behavior!
