### ISSUE TITLE
GitHub docker build action seems broken

### ISSUE THREAD

**Issue by pierotofy** [LibreTranslate/LibreTranslate#184]
Not a big deal, I don't think too many people are using it, but something is broken with the permissions (probably an expired token).

```
a6f99927f447: Waiting
ba56c40002df: Waiting
07f0380fdb5c: Waiting
9321ff862abb: Waiting
denied: permission_denied: create_package
Error: Process completed with exit code 1.
```

**Comment by nettnikl** [comment]
I'd recommend to set the token to one year instead of the default max of a few months, as it is probably only used in one repository+only has the minimum permissions.
