### ISSUE TITLE
PyPI package is broken on archlinux, need for new pyicu (2.8)

### ISSUE THREAD

**Issue by eugenemw** [LibreTranslate/LibreTranslate#189]
Now `archlinux` installs `libicui18n.so.70` which is supported by `pyicu==2.8` onwards.
Similar to #138

**Comment by PJ-Finlay** [comment]
For the next release we could do `pyicu>=2.8` instead of pinning a specific version for easier upgrades since pyicu depends on OS libraries.

**Comment by PJ-Finlay** [comment]
Yes, we've done PyPI releases less frequently than Docker.

To fix PyPI install for Arch we need to upgrade the pyicu version in requirements.txt and then push a new release to PyPI.

**Comment by PJ-Finlay** [comment]
Another more difficult long term fix is to do transliteration at the neural network level. This could be done by either collecting or generating data of the desired transliteration and training the seq2seq model on it.

**Comment by xenomorph1096** [comment]
Umm, Maybe this issue needs to be reopened? Since my up-to-date arch installs `libicui18.so.71.1`,`libicui18.so.71` and `libicui18.so` . Is this issue going to persist if the arch repos are ahead of the pypi package?

**Comment by xenomorph1096** [comment]
Yes, I think that is the issue. So would you say I should ask the maintainers of https://archlinux.org/packages/community/x86_64/python-pyicu/ about this?
