### ISSUE TITLE
https page not rendering correctly

### ISSUE THREAD

**Issue by happening-primal** [LibreTranslate/LibreTranslate#199]
As the title says, the https version of the libretranslate input page isn't rendering properly for me (see below example of what it looks like).  If I visit the http version, it is fine, looks and functions as expected.  The non-functioning https page acts as though there is no javascript, but just a guess.  This is running on a VPS (Ubuntu) with SWAG acting as a reverse proxy, all using docker.  Part of my docker-compose.yml file is at the very bottom of this post.

Tried multiple browsers, multiple machines, all the same...

warning

[[ error ]]
Dismiss
Translation API
Translate from
swap_horiz Translate into
Text to translate
[[ inputText.length ]] / [[ charactersLimit ]]
Translated text
Supported file formats: [[ supportedFilesFormatFormatted ]]
File
[[ inputFile.name ]]
Download

Request

==========docker-compose.yml snippet============

  translate:
    image: libretranslate/libretranslate
    #build: .
    ports:
      - 5000:5000
    networks:
      - internet
      - no-internet
    deploy:
      restart_policy:
       condition: on-failure
    command: --ssl

=============================================

**Comment by pierotofy** [comment]
Hmm, this sounds like a setup/configuration issue and not a bug; could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by happening-primal** [comment]
> Hmm, this sounds like a setup/configuration issue and not a bug; could we move this conversation over to the forum at https://community.libretranslate.com? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍

Sure.  For anyone wanting to know the answer to this it is that libretranslate needs to run on a subdomain rather than a subfolder of you are using a reverse proxy like nginx.  Think this is ok to close.
