### ISSUE TITLE
Issues with Docker build for offline use.

### ISSUE THREAD

**Issue by bigjohn101** [LibreTranslate/LibreTranslate#200]
****************************************
Having issues using Docker build, so i can use it offline. I run the command below;

docker build --build-arg with_models=true -t libretranslate .

Then i get this error below.

ModuleNotFoundError: No module named 'polyglot' 

Does anyone know a work around?

**Comment by lizongshen** [comment]
I have the same problem. Who knows the solution？

**Comment by dingedi** [comment]
I just tried and got no errors. Do you still get the error using the latest sources? `git pull` in the libretranslate folder
