### ISSUE TITLE
Module argostranslatefiles missing

### ISSUE THREAD

**Issue by ScobraScope** [LibreTranslate/LibreTranslate#201]
Hey. I'm installing directly from GitHub via python. It seems that the file main.py requires the module `argostranslatefiles`. I checked and there is no module like that available.  `pip3 install argostranslatefiles` just throws an error that there is no such module. There is nothing in the documentation on how to obtain it, so please help me out here.

**Comment by dingedi** [comment]
Hi,

You need to do pip install  
 ​argos-translate-files

**Comment by ScobraScope** [comment]
In that case, it's defined wrong in the dependencies.

**Comment by superherowcw** [comment]
ModuleNotFoundError: No module named 'argostranslatefiles'

**Comment by superherowcw** [comment]
> ModuleNotFoundError: No module named 'argostranslatefiles'

pip3 install argos-translate-files
