### ISSUE TITLE
Possible related multiple duplication triggers

### ISSUE THREAD

**Issue by sergioblabla** [LibreTranslate/LibreTranslate#210]
Hello there,

thank you for the API. I wonder if it is a bug you already know or perhaps some dataset model issue:

**### First sample** 

https://libretranslate.com/?source=sv&target=de&q=Black

_Trigger: wrong language (black is english not swedish)_

![image](https://user-images.githubusercontent.com/18221529/152890115-ad2f2ff1-9129-4c11-8e18-6a200363697f.png)

**### Second sample** 

https://libretranslate.com/?source=pt&target=en&q=colorido

_Trigger: no wrong language detection used_

![image](https://user-images.githubusercontent.com/18221529/152890206-27886083-932e-4f6a-b7e6-3ee9906f6cdb.png)

I'm currently fixing it from my code using RegEx. I'm sorry but I'm quite busy within my current conditions and don't have the time to go through the LibreTranslate code yet.

**Comment by dingedi** [comment]
@PJ-Finlay good case to try the penalty repeat.
setting it to 2 in translate_batch:
`./bin/argos-translate --from-lang=sv --to-lang=de "Black"
Schwarz Schwarz Schwarz
`
to
`./bin/argos-translate --from-lang=sv --to-lang=de "Black"
Schwarz
`
