### ISSUE TITLE
How to change the base href of the index.html served by the Docker image?

### ISSUE THREAD

**Issue by maiermic** [LibreTranslate/LibreTranslate#212]
I'm trying to modify the index.html of the Docker image. I create a copy of the original file of the container (using `docker cp`) on my host, modify it (add `base` element to `head`)

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<base href="https://my.domain/libretranslate/">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>LibreTranslate - Free and Open Source Machine Translation API</title>
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
...
```

 and mount it as volume in my `docker-compose.yml` using

```yml
volumes:
      - ./libretranslate_index.html:/app/app/templates/index.html
```

However, the changes are not reflected by the server. I still get the original file (without the `base` element), i.e. if I run

```
curl https://my.domain/libretranslate/ | head
```

I get

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>LibreTranslate - Free and Open Source Machine Translation API</title>
	<link rel="shortcut icon" href="/static/favicon.ico">
...
```

I also tried debug mode by adding

```yml
environment:
      LT_DEBUG: 'true'
```

to my `docker-compose.yml`.  Do I have to change something else or run a specific command to update the template?

**Comment by ecxod** [comment]
https://releasehub.com/blog/how-to-edit-a-file-in-a-docker-container

**Comment by maiermic** [comment]
Editing the file as I described works. It is changed in the container on/before start.

> However, the changes are not reflected by the server. I still get the original file (without the base element)

Maybe I changed the wrong file :confused: :question:
