### ISSUE TITLE
Turkish totally broken

### ISSUE THREAD

**Issue by sgehrman** [LibreTranslate/LibreTranslate#213]
Just installed on linux.

pip install libretranslate

The libretranslate website works, but not my localhost:5000

![gnome-shell-screenshot-IUGQH1](https://user-images.githubusercontent.com/287137/154641477-67d24b3f-4c44-4723-86e6-e496876f2c16.png)

**Comment by pierotofy** [comment]
Another "salad" case #46

**Comment by dingedi** [comment]
> Another "salad" case #46 

Note sure because this one is only in local and not on libretranslate.comv, i will check it when i have time

**Comment by pierotofy** [comment]
I wonder if it's because we haven't released in a while to PyPI. I've just released `1.2.7`, perhaps waiting for the package to update and then running `pip install -U libretranslate` should fix this?

**Comment by sgehrman** [comment]
didn't seem to help?  Should I keep waiting for a 1.2.7?

$ pip install -U libretranslate
Requirement already satisfied: libretranslate in /home/steve/.local/lib/python3.9/site-packages (1.2.5)
Collecting libretranslate
  Using cached libretranslate-1.2.5-py3-none-any.whl (386 kB)
  Downloading libretranslate-1.2.4-py3-none-any.whl (386 kB)
     |████████████████████████████████| 386 kB 2.6 MB/s 
Requirement already satisfied: Flask-Limiter==1.4 in /home/steve/.local/lib/python3.9/site-packages (from libretranslate) (1.4)
...

**Comment by pierotofy** [comment]
>  I assume that's the latest code? 

Yep that should be the latest.

**Comment by dingedi** [comment]
There must be a problem because on PyPI the latest version is 1.2.5 [https://pypi.org/project/libretranslate/#history](https://pypi.org/project/libretranslate/#history)

**Comment by pierotofy** [comment]
Ah, you're right, the CI was failing. I should have fixed it and 1.2.7 is now online. So try updating again and see if the issue persists!
