### ISSUE TITLE
docker-compose doesn't work

### ISSUE THREAD

**Issue by sgehrman** [LibreTranslate/LibreTranslate#214]
docker-compose up -d --build

Successfully built 91bea79a6b4d
Successfully tagged libretranslate_libretranslate:latest
Starting libretranslate ... done
Attaching to libretranslate
libretranslate    | Traceback (most recent call last):
libretranslate    |   File "/usr/local/bin/libretranslate", line 5, in <module>
libretranslate    |     from app.main import main
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/app/__init__.py", line 12, in <module>
libretranslate    |     from .main import main
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/app/main.py", line 5, in <module>
libretranslate    |     from app.app import create_app
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/app/app.py", line 9, in <module>
libretranslate    |     from flask import Flask, abort, jsonify, render_template, request, url_for, send_file
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
libretranslate    |     from . import json
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
libretranslate    |     from itsdangerous import json as _json
libretranslate    | ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)

**Comment by sgehrman** [comment]
I read somewhere to add this to requirements

itsdangerous==1.1.0
markupsafe==1.1.1

seems to work

**Comment by sgehrman** [comment]
Downloading English → Greek (1.5) ...
Cannot update models (normal if you're offline): IncompleteRead(124911360 bytes read, 108735 more expected)
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 116, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 136, in create_app
    frontend_argos_language_source = languages[0]
IndexError: list index out of range
INFO:apscheduler.scheduler:Scheduler has been shut down

**Comment by sgehrman** [comment]
libretranslate    | Downloading English → Irish (1.1) ...
libretranslate    | Cannot update models (normal if you're offline): IncompleteRead(98802560 bytes read, 54633 more expected)
libretranslate    | Traceback (most recent call last):
libretranslate    |   File "/usr/local/bin/libretranslate", line 8, in <module>
libretranslate    |     sys.exit(main())
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/app/main.py", line 116, in main
libretranslate    |     app = create_app(args)
libretranslate    |   File "/usr/local/lib/python3.8/site-packages/app/app.py", line 136, in create_app
libretranslate    |     frontend_argos_language_source = languages[0]
libretranslate    | IndexError: list index out of range

**Comment by dingedi** [comment]
[argostranslate](https://github.com/argosopentech/argos-translate) now automatically retries download if download fails and uses multiple cdns which solves these model download problems
https://community.libretranslate.com/t/improving-package-download/213/2
