### ISSUE TITLE
Loss of capitalization (first character, units, abbreviations)

### ISSUE THREAD

**Issue by stephanepoinsart** [LibreTranslate/LibreTranslate#224]
Hello,

I'm looking to use LibreTranslate for science content, the result is really good except one problem : often, the capitalization is lost (French -> English). I just noticed it only occurs when using the input text box, and not uploading a document (tested it with the libretranslate website), so not all use cases will be impacted.

The two conditions I noticed is either : 

* The first word of a sentence
* Units, element names, technical abbreviation that should not be translated and capitalization should be kept as is.

The second one can lead to misunderstandings, so some scientist could be quite annoyed.

Sometime it depends of the text around.

Source : 

> Le CamelCase est un style d’écriture en programmation.
> 
> En biologie on parle des PhoQP et c’est important.
> 
> Les concentrations de Ca2+ et de Mg2+ sont élevées (~ 100 nM).
>
> Et 10 KBps n'est pas 10 Kbps car c'est une autre unité.

Translation : 

> the camelcase is a writing style in programming.
> 
> in biology we speak of phoqp and it is important.
> 
> Ca2+ and mg2+ concentrations are high (~100 nm).
>
> and 10 kbps is not 10 kbps because it's another unit.

**Comment by dingedi** [comment]
This problem is more related to models and argos-translate, you can open an issue directly on the [argostranslate github](https://github.com/argosopentech/argos-translate)
