### ISSUE TITLE
docker run -ti --rm -p 5000:5000 libretranslate/libretranslate error

### ISSUE THREAD

**Issue by wuruile** [LibreTranslate/LibreTranslate#225]
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Cannot update models (normal if you're offline): IncompleteRead(11160960 bytes read, 109665810 more expected)

**Comment by dingedi** [comment]
I tried and it works. probably a network bug as @pierotofy said. argostranslate now automatically retries download if download fails and uses multiple cdns
