### ISSUE TITLE
please, how to get languages ?

### ISSUE THREAD

**Issue by wuruile** [LibreTranslate/LibreTranslate#226]
$ python main.py
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Cannot update models (normal if you're offline): IncompleteRead(81820800 bytes read, 48870 more expected)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
