### ISSUE TITLE
termux (terminal android)

### ISSUE THREAD

**Issue by code-Nea** [LibreTranslate/LibreTranslate#228]
es posible instalar el traductor a Termux?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by Benjamin-Loison** [comment]
For reference: [LibreTranslate/LibreTranslate/issues/447](https://github.com/LibreTranslate/LibreTranslate/issues/447)
