### ISSUE TITLE
argostranslategui not detected as installed?

### ISSUE THREAD

**Issue by Tarcaxoxide** [LibreTranslate/LibreTranslate#236]
if i run `./LibreTranslate/env/bin/argos-translate-gui`
it tells me to install `argostranslategui` but I already have it installed.

```
$find -iname 'argostranslategui'
./.local/lib/python3.8/site-packages/argostranslategui
```

**Comment by dingedi** [comment]
it's more an [argos-translate](https://github.com/argosopentech/argos-translate) issue.
but i tried and installing no problem argostranslategui launches fine. could you open an issue on argos-translate and give more info (distribution, version, etc)?
