### ISSUE TITLE
I can't seem to install the models, I suspect some kind of timeout.

### ISSUE THREAD

**Issue by Tarcaxoxide** [LibreTranslate/LibreTranslate#240]
running `./LibreTranslate/install_models.py`
i get
```sh
Updating language models
Found 54 models
Downloading Arabic → English (1.0) ...
Traceback (most recent call last):
  File "/home/libretranslate/./LibreTranslate/install_models.py", line 6, in <module>
    check_and_install_models(force=True)
  File "/home/libretranslate/LibreTranslate/app/init.py", line 54, in check_and_install_models
    download_path = available_package.download()
  File "/home/libretranslate/.local/lib/python3.9/site-packages/argostranslate/package.py", line 198, in download
    data = response.read()
  File "/usr/lib/python3.9/http/client.py", line 476, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.9/http/client.py", line 628, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(50763840 bytes read, 31105830 more expected)
```

if this is timeout then how would i go about increasing said timeout?

**Comment by PJ-Finlay** [comment]
It looks like you're failing to download the first model from the DigitalOcean CDN, maybe try downloading them from a faster internet connection if possible.

**Comment by Tarcaxoxide** [comment]
trust me , i wish i could download them with a faster internet connection but one of those just doesn't exist around here.
but i might try the direct download. where do i put the files ones i have them?

**Comment by Tarcaxoxide** [comment]
i've also already downloaded one of these models and have tried to install it via the gui thing like a video showed but XD
./LibreTranslate/env/bin/argos-translate-gui
only contains some print functions that tell me to install argostranslategui despite it already being installed, like 2 times (different python versions)

**Comment by PJ-Finlay** [comment]
I don't think LibreTranslate comes with`argos-translate-gui` by default, you can install it separately with:
```
pip install argostranslategui

```

**Comment by Tarcaxoxide** [comment]
it doesn't , i already did that, it's installed.
```
libretranslate@localhost ~ $ find -iname 'argostranslategui'
./.local/lib/python3.8/site-packages/argostranslategui
./.local/lib/python3.9/site-packages/argostranslategui
```

**Comment by Tarcaxoxide** [comment]
still can't find it.
```
libretranslate@localhost ~ $ ./LibreTranslate/env/bin/argos-translate-gui
argos-translate-gui not installed
install with `pip install argostranslategui`
```

**Comment by PJ-Finlay** [comment]
Try installing argostranslategui in it's own virtual environment and and run it directly.

**Comment by PJ-Finlay** [comment]
You can also dowload and install models with:
```
argospm install translate-en_es

```

**Comment by PJ-Finlay** [comment]
There are also peer to peer links if you have an unreliable internet connection:

https://github.com/argosopentech/argos-translate/tree/master/p2p

**Comment by Tarcaxoxide** [comment]
im trying the virtual thing now, i've never done this before.

i've just copied the urls to a file and am using wget.

**Comment by Tarcaxoxide** [comment]
it's not an unreliable internet connection , it's just not the fastest. it's reliably slow XD

**Comment by Tarcaxoxide** [comment]
can't find it in the virtual enviroment either but. maybe its because of the version of python being specified in the path?
I'm going to copy one of the installed argostranslategui to a director without the version number and see if that helps.

**Comment by Tarcaxoxide** [comment]
nope. but as i said. idk why it just has some print functions XD if this was c++ i probably would have solved this 3 days ago.
```
libretranslate@localhost ~ $ cat ./LibreTranslate/env/bin/argos-translate-gui
#!/home/libretranslate/LibreTranslate/env/bin/python

print('argos-translate-gui not installed')
print('install with `pip install argostranslategui`')
```

but i have no idea what i'm looking at here. if there is some weird magic stuff going on with python.

**Comment by Tarcaxoxide** [comment]
so poking around with the find command i think i found it now actually.
`find -iname '*gui*'`
resulted in a few things but one of them finally opened a display that looks like the one from the video
`./.local/bin/argos-translate-gui`

**Comment by Tarcaxoxide** [comment]
will close as soon as i've tested to see if it actually installs the models.

**Comment by Tarcaxoxide** [comment]
it's working in the ./.local/bin/argos-translate-gui gui but not the web one.
idk if that's a you problem or a them problem.

**Comment by Tarcaxoxide** [comment]
ok so figured out where i need to plop those files now . /tmp/libretranslate-files-translate/
now that i think of it though that was kind of obvious and also this would explain why my temp partition ended up getting full yesterday XD.
