### ISSUE TITLE
Installation docs are not quite updated

### ISSUE THREAD

**Issue by ThraaxSession** [LibreTranslate/LibreTranslate#25]
Hey together,

I just tried installing by these commands as you described:
```
git clone https://github.com/uav4geo/LibreTranslate --recurse-submodules
cd LibreTranslate
pip install -r requirements.txt
python main.py [args]
``` 

Seems like I have to install the models by my own. Would you update the documents or do create an auto-install?

```
(venv) [me@somehostLibreTranslate]$ python3 install_models.py
Removing old /home/me/webservices/LibreTranslate/installed_models
Creating /home/me/webservices/LibreTranslate/installed_models
Installing models/ar_en.argosmodel...
Installing models/de_en.argosmodel...
Installing models/en_ar.argosmodel...
...
Installed 9 language models!
```

Your new fan. :)

**Comment by pierotofy** [comment]
Mm, typically the `main.py` code *should* (does it?) install the models on the first run if the models are not installed already. The install_models.py script will force-install the models.

Perhaps you could add a note on the README.md to document the install_models.py script?

**Comment by ThraaxSession** [comment]
Hi @pierotofy :) 

I don't think it's a good way to describe it in the README.md (as it seems to be only a workaround). If the main.py should do it, this seems to be an issue. :(
