### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by Gbambor-Jnr** [LibreTranslate/LibreTranslate#259]
hello I am trying to make an API call in react and it keeps saying i should contact the server provider for an API key!!! its just a learning practices I am trying to do and not trying to make it commercial. Please how do i go about this?

**Comment by pierotofy** [comment]
You can run your own instance if you don't want to pay for a key, or use one of the many mirrors that don't require one: https://github.com/LibreTranslate/LibreTranslate#mirrors

**Comment by Gbambor-Jnr** [comment]
Hello, I probably don’t completely understand how this works since I’m still new to all these things!!!! was just trying to make a post param call to your server so this looks a bit new to me!!! But thank you  But Thank You!!!
