### ISSUE TITLE
app.language has no attribute languages

### ISSUE THREAD

**Issue by MiguelMJ** [LibreTranslate/LibreTranslate#262]
Hi!
I'm launching the app with these options: `--load-only es,en,fr --disable-web-ui` but the models don't update: I get the following message:
```output
Cannot update models (normal if you're offline): module 'app.language' has no attribute 'languages'
```
As the message says, `app.language` has no attribute `languages`, but still it is accessed in `init.py`, lines 58 and 68.

I haven't found any other place where `app.language.languages` is used, via `grep -nr "app.language.languages"` and `grep -nr "from app.language"` so I guessed that maybe those lines were meant to access `app.language.__languages`. However changing those lines to use `app.language.__languages` only changes the error to:
```
Cannot update models (normal if you're offline): 'NoneType' object is not iterable
```
I understand that this happens because the line 58, that would assign `app.language.__languages` a value, is never executed and line 68 tries to iterate through its default value: `None`.

Some solutions I came up with:
- Change lines 58 and 68 to use `app.language.__languages` instead of `app.language.languages` and set the default value of `app.language.__languages` to `[]` instead of `None`. I don't think this is a good idea, though.
- Just add new `app.language.languages` variable with default value `[]`. Short solution, not sure if the best.

What do you think? I'm missing something? If you tell me one of those is OK I'll open a PR.
Thank you

**Comment by ServOKio** [comment]
I also have the same problem. After `[polyglot_data] Downloading package transliteration2.vi to` nothing is happening.

![2022-06-01_17-58](https://user-images.githubusercontent.com/51263003/171435890-77674e4d-9eca-409f-abcc-2d4fc537954c.png)

I tried to copy packages from my old server where everything worked, but now I get `Cannot update models (normal if you're offline): module 'app.language' has no attribute 'languages'`

**Comment by raitman005** [comment]
I tried this one and when i execute the python main.py nothing is happening.

i change the line 58 and 68 on init.py file
then change the None to [] and add languages = [] on languages.py

**Comment by aguajardo** [comment]
Has there been any progress on this? I am having the same error did the same thing and it did not work...

**Comment by Seabright22** [comment]
This issue seems to still be here (unless anyone has found another fix?), neither of the attempted solutions above work for me.

**Comment by dingedi** [comment]
I have the same error message however the api works correctly.

```
$ python3 --version
Python 3.10.6

$ pip --version
pip 22.2.2 from /home/dingedi/.local/lib/python3.10/site-packages/pip (python 3.10)

$ libretranslate --load-only es,en,fr --disable-web-ui
Cannot update models (normal if you're offline): module 'app.language' has no attribute 'languages'
```

**Comment by aguajardo** [comment]
> I have the same error message however the api works correctly.
> 
> ```
> $ python3 --version
> Python 3.10.6
> 
> $ pip --version
> pip 22.2.2 from /home/dingedi/.local/lib/python3.10/site-packages/pip (python 3.10)
> 
> $ libretranslate --load-only es,en,fr --disable-web-ui
> Cannot update models (normal if you're offline): module 'app.language' has no attribute 'languages'
> ```

Do you mean that even with the error, it still processes requests? Does it translate even with that or is it just that the api server boots up?

**Comment by dingedi** [comment]
The api works fully even with this error on my side, the message must be irrelevant but I'll look into detail when I have time.

**Comment by cemalokten** [comment]
I'm also receiving this error, any progress on it?

**Comment by pierotofy** [comment]
I can't seem to reproduce it on my machine:

```
[piero:~] [test] $ python3 --version
Python 3.10.8
[piero:~] [test] $ pip --version
pip 22.3 from /home/piero/test/lib/python3.10/site-packages/pip (python 3.10)
[piero:~] [test] $ libretranslate --load-only es,en,fr --disable-web-ui
Updating language models
Found 58 models
...
```

**Comment by pierotofy** [comment]
I suspect these issues have been fixed since I can't reproduce them with the latest version. If the issue persists, feel free to re-open this? :pray:
