### ISSUE TITLE
API not translate full content

### ISSUE THREAD

**Issue by raitman005** [LibreTranslate/LibreTranslate#270]
Hello,

I’m planning to buy the api-key but first i tested it on your website, some texts doesn’t translated. Is it possible to add a words to translate in your api?

Thank you

**Comment by PJ-Finlay** [comment]
You can contribute data to LibreTranslate by making a `/suggest` request to https://libretranslate.com which will be added to the [LibreTranslate Community Dataset](https://github.com/LibreTranslate/CommunityDS) after review.
