### ISSUE TITLE
docker-compose build do not install all/requested languages

### ISSUE THREAD

**Issue by Apollon77** [LibreTranslate/LibreTranslate#271]
Hi,

I iinstalled Libretranslate via "docker-compose up -d --build" and wondered why only some translation options were available (kind of the first 10ish he also downloads when you run install_models.py ... so I needed to install that command manually in the docker container.

Should this not be done on build time?

**Comment by PJ-Finlay** [comment]
Likely your model download failed somehow, but without logs it's hard to say exactly why.

You can include the models (currently 7GB for all languages) in the Docker image build with ` --build-arg with_models=true `.

**Comment by Apollon77** [comment]
> Likely your model download failed somehow, but without logs it's hard to say exactly why.

Interetingly I did not found anything in logs that started the download progress at all ...
