### ISSUE TITLE
 'app.language' has no attribute 'languages'

### ISSUE THREAD

**Issue by Vabel404** [LibreTranslate/LibreTranslate#281]
(py_translate) D:\temp_dev\translate>libretranslate
Cannot update models (normal if you're offline): module 'app.language' has no attribute 'languages'

when i first time to start this program,it is work,
but i Ctrl + C interrupt ,because it language mode download ' v  is let me down
and then 
it can not download any language mode now.
![1656324709630](https://user-images.githubusercontent.com/78469819/175918269-928e963c-5058-4a69-9c2a-c46c1f5c67fb.jpg)

**Comment by dingedi** [comment]
Duplicate of https://github.com/LibreTranslate/LibreTranslate/issues/262
