### ISSUE TITLE
No support for arm (Apple M1, Raspberry PI)

### ISSUE THREAD

**Issue by ecx0d** [LibreTranslate/LibreTranslate#289]
I simply run this : (as described in the README.md)
```
docker run -ti --rm -p 5000:5000 libretranslate/libretranslate
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Comment by ecx0d** [comment]
I have only reproduced the error message. The attempt was on a Raspberry, therefore "arm/V7".
Please build also for raspberry. There are milions of little raspberries waiting in line outside to be given a container.

**Comment by pierotofy** [comment]
Feel free to open a pull request and help us add support for it.

**Comment by markbattistella** [comment]
In case anyone want to run it on an M1 now, until the available build, you can run it with the `--platform linux/amd64` flag: `docker run --platform linux/amd64  -ti --rm -p 5000:5000 libretranslate/libretranslate`

**Comment by ecx0d** [comment]
this don't work
```
# docker run --platform linux/amd64 -ti --rm -p 5000:5000 libretranslate/libretranslate
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by dingedi** [comment]
@ecx0d could you open a pull request to make it work ?

**Comment by ecx0d** [comment]
are you trying to be ironic right now?
