### ISSUE TITLE
Polish lang not working

### ISSUE THREAD

**Issue by fairking** [LibreTranslate/LibreTranslate#290]
Hi guys,

I wanted to test the website libretranslate.com but it looks like the polish language is not working. Looks like a bug.

![Screenshot_20220731-154155](https://user-images.githubusercontent.com/13495631/182031616-f58f6b51-6717-4ae1-9fd7-35b1a8273dc1.png)

Also the dark mode on desktop does not show a list of languages properly in the dropdown/switch.

**Comment by dingedi** [comment]
I just looked and it seems to be more a problem of the argostranslate model which translates badly hello, because other words sentences are translated well.

**Comment by fairking** [comment]
> I just looked and it seems to be more a problem of the argostranslate model which translates badly hello, because other words sentences are translated well.

I don't understand what you say. Is translator not able to translate the word "hello"? Is it a bug?

**Comment by dingedi** [comment]
LibreTranslate is a web interface for [Argos Translate](https://github.com/argosopentech/argos-translate) who does the translations, the problem seems to come from the Argos Translate models.

**Comment by fairking** [comment]
I don't think this translator is useful at all. I am sorry guys but the tranlation result is unacceptable. I would not use it in any circumstances. Please consider to improve the quality. Even my old offline dictionary based translator did the job much better than that.

LibreTranslate:
![Screenshot_20220821-131905](https://user-images.githubusercontent.com/13495631/185790774-8f969675-0be6-4f48-bf0d-f4488caa31b8.png)

Google translator:
![Screenshot_20220821-131953](https://user-images.githubusercontent.com/13495631/185790785-5b39c347-06ec-4ff1-b70d-b2eb506ca8d1.png)

**Comment by argosopentech** [comment]
It looks like the Polish model could use improvement. If anyone wants to train a new Polish model I can add it to the package index.

- https://community.libretranslate.com/t/contributing-a-trained-language-model-package-to-argos-translate/308
