### ISSUE TITLE
can't build using docker-compose

### ISSUE THREAD

**Issue by tassoman** [LibreTranslate/LibreTranslate#292]
Hello, I've just tried to run `docker-compose up -d --build` but it failed at step 6 of 13:

```bash
Step 6/13 : RUN apt-get update -qq   && apt-get -qqq install --no-install-recommends -y cgroup-tools libicu-dev pkg-config gcc g++   && apt-get clean   && rm -rf /var/lib/apt
 ---> Running in d0f8457d6dd2
 cgroups: cgroup mountpoint does not exist: unknown
 ERROR: Service 'libretranslate' failed to build : Build failed
```

I've also tried to edit Dockerfile, [adding packet](https://github.com/docker/for-linux/issues/219#issuecomment-1197780243) `cgroup-tools` but with no luck.

**Comment by dingedi** [comment]
I personally don't have any errors, could you give us the info of your operating system and docker & docker-compose?

**Comment by tassoman** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

Linux hostname 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Docker version 19.03.9, build 9d988398e7
docker-compose version 1.29.2, build unknown

I hope it can helps! :information_source:

**Comment by dingedi** [comment]
It might be the docker version, the only difference on my computer is:
docker: 
```
$ docker -v
Docker version 20.10.17, build 100c701
```
and docker-compose
```
$ docker-compose -v
Docker Compose version v2.7.0
```

**Comment by tassoman** [comment]
As far I can remember, I've installed official DEBs packages, only. Are you running [official docker installation](https://docs.docker.com/engine/install/ubuntu/)? :thinking:

**Comment by dingedi** [comment]
I use Docker Desktop, i think it provide latest version. But it's strange because it could work with your Docker and docker-compose version.

**Comment by tassoman** [comment]
Really I dunno either... As host, I have the packet installed, I'm going to try on a different system.

`ii | cgroup-tools | 2.0-2 | amd64 | control and monitor control groups (tools)`

python venv pip installation works flawless ...

**Comment by tassoman** [comment]
An update: after reading this page, I [found a comment saying](https://forum.garudalinux.org/t/fresh-install-docker-cgroup-mountpoint-does-not-exist/1684/24) cgroup support changed inside docker, since 20.10.
So I apt purged Ubuntu's packaging (ver. 19.x) and did a full installation as seen on official Docker's documentation. 
Now I have a working 20.10.17 version too and build problems are gone.
