### ISSUE TITLE
Packaging for pip-based distribution

### ISSUE THREAD

**Issue by Arteneko** [LibreTranslate/LibreTranslate#30]
Hello, I was wondering if we could expect the project to have, as goal, pip-based releases (e.g. wheel builds or tgz archives) ?

This would *greatly* simplify setup and updates, including dependency management.

**Comment by pierotofy** [comment]
Hey @Arteneko :hand: sounds like it would be a useful thing to have. Would you be interested in helping us setting it up?

**Comment by Arteneko** [comment]
Probably, once I get around setting up a server and tweaking a bit with the tool itself.

**Comment by vemonet** [comment]
I can give a hand on setting the pip package, and the automated release pipeline to publish to pypi 

For the models issue @pierotofy you could add a check for a LibreTranslate models folder when starting using the API, if no model found it downloads the models repo, and unzip it (or allow users to provide the models path through a parameter)

To make it generic using a hidden folder in the home folder is a quick and (too?) popular option that will work well on all platforms and containers

Something like `~/.translate_models`, `~/.translate/models`, or `~/.libretranslate/models` if you want to also store other thing than models

**Comment by pierotofy** [comment]
I think you're spot on. `~/.libretranslate/models` probably is best, since it allows space for other future uses.

**Comment by PJ-Finlay** [comment]
Is this to store downloaded but not installed models? [Argos Translate stores installed models at `~/.argos-translate/packages`](https://github.com/argosopentech/argos-translate/blob/6a0f389caccd35645049f00658636b5c007b98a8/argostranslate/settings.py#L7) and the plan was to store downloaded models at `~/.argos-translate/downloads`. This may be best managed at the Argos Translate layer.

Related issue: https://github.com/argosopentech/argos-translate/issues/7

Ideally we could store model metadata in a JSON file with download links to the GitHub URL to allow for fine grained programmatic downloading.

**Comment by Arteneko** [comment]
Ideally, instead of polluting the user namespace, such files should probably be stored under `~/.local/share/` (or `~/.local/cache`, depdending on the use case) as per the XDG spec.

**Comment by pierotofy** [comment]
+1 for adding this to Argos Translate.

**Comment by PJ-Finlay** [comment]
TIL: https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by PJ-Finlay** [comment]
I think downloads should go at `~/.local/cache/argos-translate/downloads` and installs should go at `~/.local/share/argos-translate/packages`. We should also check the value of the `$XDG_CACHE_HOME` and `$XDG_DATA_HOME
` environments. `setup.py` should also support removing these automatically.

**Comment by vemonet** [comment]
Re-using Argos files is definitely the best way to go. Thanks @Arteneko for the detail on XDG spec, I learned something too

So I guess @PJ-Finlay you plan to implement init/download models methods in `argos` that could be directly reused in LibreTranslate to handle the models? 

Then no more git submodule, and a pip package can easily be setup

**Comment by PJ-Finlay** [comment]
I added XDG compliance, going to try to work on automated downloads this weekend.

I was hoping that there was a field to add to setup.py to list directories to delete on uninstall. It looks like it's not that simple (https://gist.github.com/myusuf3/933625). I think it's fine to just not delete data/cache files on uninstall, it doesn't seem like Python packages are expected to do this automatically. Additionally, deleting files on users systems without their knowledge is a potentially risky operation.

**Comment by pierotofy** [comment]
I think it's fine to leave the cached/downloaded files on uninstall.

**Comment by PJ-Finlay** [comment]
Downloading packages is implemented now. @pierotofy  Let me know when you're ready/if you have suggestions for changes and I'll make `argostranslate==1.1.0`. Downloading packages is documented in the [package module docs](https://argos-translate.readthedocs.io/en/latest/source/argostranslate.html#module-argostranslate.package), TLDR:
```
from argostranslate import package

# Update package definitions from remote
package.update_package_index()

# Load available packages from local package index
available_packages = package.load_available_packages()

# Download and install all available packages
for available_package in available_packages:
    download_path = available_package.download()
    package.install_from_path(download_path)
```

**Comment by pierotofy** [comment]
This is gold; it will simplify some of the stuff in libretranslate. I'll test in the upcoming days, but seems good to me if you want to go ahead and release.

**Comment by PJ-Finlay** [comment]
`1.1.0` live on PyPI.

**Comment by pierotofy** [comment]
Updated to use `1.1.0` https://github.com/uav4geo/LibreTranslate/commit/9191524c04be8b87f27cce607588c538f0c96e04, removed models submodule. This should simplify the creation of a pip package quite a bit!

**Comment by vemonet** [comment]
Nice! I started to define the pip package

I am getting this error when running `main.py` with current main branch though:
```bash
python3 main.py
```

Error message:
```
/home/.argos-translate/packages
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    frontend_timeout=args.frontend_timeout)
  File "/home/LibreTranslate/app/app.py", line 17, in create_app
    from app.init import boot
  File "/home/LibreTranslate/app/init.py", line 3, in <module>
    from argostranslate import settings, package, translate
  File "/home/.local/lib/python3.6/site-packages/argostranslate/settings.py", line 33, in <module>
    shutil.copytree(legacy_package_data_dir, package_data_dir, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
```

The argos version installed seems to be the expected one:

```bash
pip install -r requirements.txt 
Requirement already satisfied: argostranslate==1.1.0 in /home/vemonet/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.1.0)
```

I also tried with python3.7 and virtual environment but got the same error

Any idea what it is due to @PJ-Finlay ?

**Comment by PJ-Finlay** [comment]
Yikes, looks like that parameter was added in Python 3.8.

[3.7 docs](https://docs.python.org/3.7/library/shutil.html#shutil.copytree)
[3.8 docs](https://docs.python.org/3.8/library/shutil.html#shutil.copytree)

Not exactly sure what to do here, either require a higher Python version or try to add some compatibility code. Looking into it more now.

**Comment by PJ-Finlay** [comment]
Ok, should be fixed in source. If Python < 3.8 it doesn't allow auto upgrading Argos Translate data dir to a directory already exists but won't crash.

**Comment by PJ-Finlay** [comment]
`1.1.1` is live on PyPI, good catch @vemonet.

**Comment by PJ-Finlay** [comment]
JK `1.1.2`

**Comment by vemonet** [comment]
Thanks @PJ-Finlay ! The classic Python version issue, I thought of it but could not find python version disclaimer in argos-translate docs

If I have time I will quickly add basic testing to run through GitHub Actions to make sure the packages worked on specific versions

I'll try it asap

**Comment by PJ-Finlay** [comment]
Is this for Argos Translate or LibreTranslate? The plan is to use GitLab for Argos Translate CI.

https://github.com/argosopentech/argos-translate/issues/30

https://github.com/argosopentech/argos-translate/issues/11

**Comment by vemonet** [comment]
I added the pip package and detailed all changes here: https://github.com/uav4geo/LibreTranslate/pull/37

@PJ-Finlay 
GitHub Actions vs GitLab CI is basically the same if you just aim to do basic `pytest` run

imo the best is to just use the one where your host your code, apart if you need specific features from the other CI

From my experience GitLab CI is more mature and give more possibilities when it comes to deploy self-hosted runners anywhere (e.g. kubernetes). GitHub Actions is working on it

But also from my experience GitHub Actions is much more user-friendly, as it is built for developers, not sysadmin/DevOps (GitLab is more technical). Secrets are much easier to set in GitHub Actions

I even have been using GitHub Actions for long data processing workflows, and it's really stable and easy to maintain

For short, in my opinion:
* You are a developer who's building an open source library hosted on GitHub, and you want to quickly get your things done without the need to know Linux arcanes (thanks the actions marketplace)? Use GitHub Actions
* You are a developer who is building libraries on GitLab (gitlab.com or self-hosted), or you want to deploy complex workflow to various self-hosted platforms? Go with GitLab CI

In our case it does not really matter, the same pytest can be easily run on GitLab CI or GitHub Actions, you just need to put the bash commands in a different YAML format :)

**Comment by PJ-Finlay** [comment]
Thanks for the information, I hadn't looked into the differences too much. It sounds like for these purposes the differences are pretty small, but I already use GitLab for [my website](https://www.argosopentech.com) so probably want to stick with it. Now that automatic package downloading is working writing some real unit tests is possible.
