### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by rio-codes** [LibreTranslate/LibreTranslate#302]
I got this error last night:

![JSON-unexpectedcharacter](https://user-images.githubusercontent.com/791713/185994582-23144176-aaf5-4ce5-a9ca-e7fefac0e4bc.png)

The first character in the word I posted was ע. (Language: Hebrew)
I am wondering if this is related to the language being read right-to-left? I brought this up in #301 . 

After I got the error, the website was inaccessible with an error 502, verified by https://downforeveryoneorjustme.com/ . Not sure if this was just a coincidence, or if this was a terminating error.

**Comment by dingedi** [comment]
I checked and there is indeed a bug, if we translate this character from hebrew to arabic for example
[https://libretranslate.com/?source=he&target=ar&q=%2520%25D7%25A2](https://libretranslate.com/?source=he&target=ar&q=%2520%25D7%25A2)

**Comment by PJ-Finlay** [comment]
The issue also occurs when translating the English word "by" to Arabic.

https://libretranslate.com/?source=en&target=ar&q=by

**Comment by rio-codes** [comment]
> The issue also occurs when translating the English word "by" to Arabic on https://libretranslate.com but not on https://libretranslate.de. I think this could be related to #295.

Did applying your fix from #295 resolve this error?

**Comment by PJ-Finlay** [comment]
I think it should
