### ISSUE TITLE
Direct Translation via URL request doesn't seem to work

### ISSUE THREAD

**Issue by petrarca-arezzo** [LibreTranslate/LibreTranslate#306]
I wanted to directly get translations via the URL - e.g. load the translation with something like:

`https://libretranslate.com/?source=en&target=fr&q=I%2520love%2520it%21`

Unfortunately, this doesn't seem to work as only the source text is shown - even if I reload the page or press the "Translate Text" button, nothing happens. Only if I start editing the source text the translation shows up eventually.

I'm using Firefox 103 currently.

**Comment by dingedi** [comment]
indeed it is not yet implemented so it's not a bug, for the moment it just allows to restore the correct language and the text but it does not restart the translation.

but it would be a good improvement

**Comment by satoshinotdead** [comment]
There is no progress? I'm interested on that (probably start to play around with the API and N8N soon) :)
