### ISSUE TITLE
Translate File Using Curl Fails

### ISSUE THREAD

**Issue by nobicycle** [LibreTranslate/LibreTranslate#307]
Hello and thanks to all developers on this project.

Using:
$`curl -X POST --silent --show-error -F source=en -F target=id -F file='test.txt' http://127.0.0.1:5000/translate_file`

I get the following error:

127.0.0.1 - - [07/Sep/2022 21:00:03] "POST /translate_file HTTP/1.1" 400 -
{"error":"The browser (or proxy) sent a request that this server could not understand."}_

This seems related to issue #305 

The web version works fine, including translate file.

**Comment by archeus** [comment]
the `file` parameter should be sent like ` -F 'file=@test.txt'`. From `man curl`: 
``` To force the 'content' part to be a file, prefix the file name with an @ sign.```

So the full CURL command would be: 
```
curl -X POST --silent --show-error -F source=en -F target=id -F file='test.txt' http://127.0.0.1:5000/translate_file
```
