### ISSUE TITLE
Batch of text translation did not work

### ISSUE THREAD

**Issue by mrtushartiwari** [LibreTranslate/LibreTranslate#309]
Version : libretranslate-1.2.9
OS : Ubuntu 18.04.6 LTS

Started the using `python main.py --load-only en,hi --host 127.0.0.1 --port 5000`

Its used for English to Hindi translation.

`
import json
import requests
API_URL = "http://127.0.0.1:5000/translate"

params = {
    'q': ["3 students die in wall collapse in Jharkhand", 
          "Cabinet okays major changes in terror law"],
    'source': "en",
    'target': "hi",
    'format': "text"
}

r=requests.post(url = API_URL, data = params)

translated_text = r.json(encoding='utf-8')
print(translated_text)  #  output is {'translatedText': 'बीबीसी की रियलिटी टीवी एम्स पर ध्यान केंद्रित करेगा'}

`
from  tests/test_api/test_api_translate.py  and test_api_translate_batch test case
I expected the a batch of reponse.

In above example 2 translated sentences.

**Comment by dingedi** [comment]
it's because you have to encode the array of texts to be translated in json before sending it. you can do this with json.dumps for example

```python
params = {
'q': json.dumps(["3 students die in wall collapse in Jharkhand",
"Cabinet okays major changes in terror law"]),
'source': "en",
'target': "hi",
'format': "text"
}
```
