### ISSUE TITLE
libretranslate.de is down

### ISSUE THREAD

**Issue by martinval11** [LibreTranslate/LibreTranslate#319]
![Screenshot_2022-09-24_08-16-25](https://user-images.githubusercontent.com/100082171/192094953-fb790235-910f-4ece-86a8-fa654049dad2.png)
Is libretranslate.de down?

**Comment by dingedi** [comment]
it is not related to the LibreTranslate project.
But otherwise the website seems to be functional and up: [https://www.isitdownrightnow.com/libretranslate.de.html](https://www.isitdownrightnow.com/libretranslate.de.html)

**Comment by pierotofy** [comment]
Yes we have no affiliation with https://libretranslate.de (I have no idea who registered it). It is down as well for me: https://libretranslate.de/
