### ISSUE TITLE
HTML tags returned by API

### ISSUE THREAD

**Issue by rccarlson** [LibreTranslate/LibreTranslate#321]
The Azerbaijani text ``` Xüsusi, Qeyd 9:15 Yeni Hive. ``` is translated as ```Allowed HTML tags: <a> <em> <strong> <cite> <code> <ul> <ol> <li> <dl> <dt> <dd>.```. 

Google Translate translates it as `Special, Note 9:15 New Hive.`, which admittedly also doesn't make sense, but I'm fairly certain the text is not talking about HTML tags.

![image](https://user-images.githubusercontent.com/43221493/192859772-2e489d2a-a0de-45c3-96d3-57006152621a.png)

![image](https://user-images.githubusercontent.com/43221493/192858942-551bed8f-b944-4d06-be07-a5a70fe66635.png)

This issue is very specific to this text. Small changes to the text will cause the HTML tags to not be included

**Comment by PRO-BROS** [comment]
Wow! I never try this method in my [website](https://prhocoding.com/)

**Comment by dingedi** [comment]
This problem is more related to models and argos-translate, you can open an issue directly on the argostranslate github
