### ISSUE TITLE
Front page of Hacker News!

### ISSUE THREAD

**Issue by PJ-Finlay** [LibreTranslate/LibreTranslate#34]
I posted a Show HN for LibreTranslate and it's on the front page:
![image](https://user-images.githubusercontent.com/13067016/107128329-5b326a80-6882-11eb-9c8c-d7e6735fcd9f.png)

**Comment by immanuelfodor** [comment]
Found the project there, thank you :)

**Comment by PJ-Finlay** [comment]
Someone added a LibreTranslate integration for their Node.js translation package: https://github.com/franciscop/translate

**Comment by pierotofy** [comment]
Oh that's awesome! Hopefully the server won't crash :p
