### ISSUE TITLE
Would be nice if 'Get API Key' page had info on the character limit

### ISSUE THREAD

**Issue by mayeaux** [LibreTranslate/LibreTranslate#341]
![Screen Shot 2022-11-11 at 9 23 14 PM](https://user-images.githubusercontent.com/7200471/201425745-098036a6-18cf-49ba-8568-dcf788ad5441.JPG)
It seems that when you get a paid key the character limit goes from 2000 to 5000, would be great if this was listed in the graphic.

Would be great if that was listed so people could know. Sorry for opening this here didn't want to register for a forum for one post.

**Comment by pierotofy** [comment]
This shouldn't be the case on libretranslate.com, the limit is (should be?) always 2,000 (with or without API key)

**Comment by mayeaux** [comment]
From this thread, it seems that with a paid key it's 2000: https://community.libretranslate.com/t/paid-api-subscription-but-too-many-requests-limitation/272/16
