### ISSUE TITLE
Can't connect to Vast.ai server running Libretranslate

### ISSUE THREAD

**Issue by mayeaux** [LibreTranslate/LibreTranslate#342]
I have LibreTranslate running on port 8080, though I can't connect to the frontend.

When I connect to `http-server` running on port 8080, via: http://76.50.42.128:49630 , it works properly, but can't connect to the LibreTranslate server. Is it something with how Vast.ai redirects their ports like above? Thanks

**Comment by pierotofy** [comment]
This is probably a question for Vasti.ai support and not a bug in LT.

**Comment by mayeaux** [comment]
Well if I can run other apps properly from that port but can't connect to the LibreTranslate server then it's something specific to how LibreTranslate's server works.

**Comment by mayeaux** [comment]
Okay I got it working using the nginx config here: https://github.com/argosopentech/LibreTranslate-init

Thanks!
