### ISSUE TITLE
incorrect translation I guess

### ISSUE THREAD

**Issue by SugarGrandma** [LibreTranslate/LibreTranslate#348]
Just wanted to say that "szklarnia" in polish is translated to "glass glass glass" instead of "greenhouse".
And that "kohlrabi" isn't translated at all and should be translated to "kalarepa".
"greenhouse" is translated to "cieplarnia" which is fine but "cieplarnia" isn't translated to the "greenhouse" and isn't translated at all. (cieplarnia and szklarnia are almost he same thing btw)
Also "glass glass glass" is translated to "szklany" and should be just "szkło szkło szkło".
"Chayote" isn't translated at all and probably should be translated to "kolczoch"

**Comment by PJ-Finlay** [comment]
If you submit your shggested translations to `libretranslate.com/suggest` we can include them in future training data.
