### ISSUE TITLE
Ability to provide already downloaded language models instead of slowly downloading them at first run

### ISSUE THREAD

**Issue by f2k1de** [LibreTranslate/LibreTranslate#349]
It would be nice if I can specify a directory with an --argument where already the downloaded files are in.
I noticed that the initial download at the first run is very slow (often below 1 Mbit/s) and it needs to do it on every installation again. To reduce the load and traffic on the already slow servers it would be nice if just one download would be necessary instead of one on every deploy.

**Comment by pierotofy** [comment]
I think this would be just a matter of mounting a volume on `/root/.local/share/argos-translate` so that models get stored there?

**Comment by ziadsarour** [comment]
I am unable to download models, it always fail for me. It would be great if we could download them from another source and mount a volume like @pierotofy said.
I can't enjoy this awesome library because of this :(

**Comment by PJ-Finlay** [comment]
What error do you get trying to download the models?

**Comment by mayeaux** [comment]
I was also having a lot of connection timeout errors when I was trying to download the models recently. Eventually succeeded but took a long time.

**Comment by pak11273** [comment]
why are models re-downloading every time i run `docker run -ti --rm -p 5000:5000 libretranslate/libretranslate`

**Comment by PJ-Finlay** [comment]
All of the models are 7-8 GB so it's recommended to not download every time you start the Docker container.

> The models are stored inside the container under /root/.local/share and /root/.local/cache. Feel free to use volumes if you do not want to redownload the models when the container is destroyed. Be aware that this will prevent the models from being updated!

You also don't have to download all of the models. You can select specific languages with: `--load-only en,de,es,fr,zh`

**Comment by pak11273** [comment]
>  Feel free to use volumes if you do not want to redownload the models when the container is destroyed. 

@PJ-Finlay Can you give an example of how to do this on Ubuntu 20.04?

**Comment by pierotofy** [comment]
This should be fixed with #366 

Use the `./run.sh` script to avoid downloading the models everytime. :clinking_glasses:

**Comment by HamzaAlwan** [comment]
@pierotofy how can I avoid downloading them using Dockerfile? Could you please share an example?

**Comment by pierotofy** [comment]
Use `./run.sh` :+1: (the script was added a few weeks ago).

**Comment by davidhealey** [comment]
@pierotofy I'm using the latest commit from the Main branch. 

```
root@DockerHost:/opt/LibreTranslate# ./run.sh                
Checking for docker...   found
Updating language models
Found 96 models
Downloading Albanian → English (1.9) ...
```
