### ISSUE TITLE
problem to change text to send

### ISSUE THREAD

**Issue by AlainRnet** [LibreTranslate/LibreTranslate#350]
I sometimes use the system of sending a translation into French that is not correct. For 1 maybe 2 weeks, the bug system: when I correct a text, the entry of a character is taken into account but it is the "Translate from" field that takes the hand. If I continue to enter, my proposal to send is then deleted and replaced by a new translation.

**Comment by pierotofy** [comment]
Should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/282737519cc3e74f09279be4da5197bccc8574b6 :pray: thanks for the report!
