### ISSUE TITLE
Turkish results duplicated

### ISSUE THREAD

**Issue by derekantrican** [LibreTranslate/LibreTranslate#351]
According to https://libretranslate.com/?source=en&target=tr&q=Hello it seems that Turkish translations are duplicated (eg "Hello" translates to "Merhaba Merhaba" and "Breakfast" translates into "Kahvaltı Kahvaltı")

**Comment by JWOverschot** [comment]
I have also seen this with English to Dutch.
For example "duty" is translated to "plicht plicht plicht..." This repeats 128 times.

![image](https://user-images.githubusercontent.com/21358884/210280912-2822983e-648e-4c1a-a8be-745c4611393e.png)

**Comment by dingedi** [comment]
This problem is more related to models and argos-translate, you can open an issue directly on the [argostranslate github](https://github.com/argosopentech/argos-translate)

**Comment by derekantrican** [comment]
@dingedi Looks like the argostranslate issue was closed - when can I expect to see the fix on the LibreTranslate site?

**Comment by dingedi** [comment]
@derekantrican 
the issue has been closed but it is not solved, this problem comes from the argostranste translation model en->tr
it is necessary to retrain a model of better quality
