### ISSUE TITLE
Licensing issue for libretranslate

### ISSUE THREAD

**Issue by ShanmukhaSridhar** [LibreTranslate/LibreTranslate#353]
We are planning to use this library in our application which is licensed under GNU Affero General Public License v3.0 causing me a risk of license. We are not doing any modifications in the source code of the library.
Can GPL and our application be made proprietary?
Can you please more insights into this?

Thanks in advance.

**Comment by pierotofy** [comment]
You should consult with a lawyer, but you most definitely cannot release LibreTranslate, or modifications of it, under a proprietary license.
