### ISSUE TITLE
ERROR: The Compose file './docker-compose.cuda.yml' is invalid

### ISSUE THREAD

**Issue by Athanaze** [LibreTranslate/LibreTranslate#354]
After a fresh git clone, when running
`docker-compose -f docker-compose.cuda.yml up -d --build`

I get
`
ERROR: The Compose file './docker-compose.cuda.yml' is invalid because:
services.libretranslate-cuda.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
`

**Comment by PJ-Finlay** [comment]
It looks like it's complaining about this line:
https://github.com/LibreTranslate/LibreTranslate/blob/b6219cb60516a0353148de59196b7a2f10a63ccd/docker-compose.cuda.yml#L15

**Comment by PJ-Finlay** [comment]
It looks like this code is [enabling GPU access for Docker](https://stackoverflow.com/questions/70761192/docker-compose-equivalent-of-docker-run-gpu-all-option). 

`docker-compose -f docker-compose.cuda.yml up -d --build` works for me with version `1.29.1`. What version are you using?
