### ISSUE TITLE
Docker image size has doubled after v1.3.0

### ISSUE THREAD

**Issue by thomas-mc-work** [LibreTranslate/LibreTranslate#359]
Hello team,

I've just spotted that the image size of the Docker image has doubled after `v.1.3.0`:

- `v.1.3.0`: 872 MB
- `v.1.3.1`: 1.8 GB

Are you aware of that resp. was that on purpose?

**Comment by pierotofy** [comment]
Mm, I didn't check (docker builds are automated), but I'm also not sure what caused the increase in size. We'd love help to find out and improve the size.

**Comment by pierotofy** [comment]
There we go:

```
463M    site-packages/nvidia/cublas
463M    site-packages/nvidia/cublas/lib
860M    site-packages/nvidia/cudnn/lib
861M    site-packages/nvidia/cudnn
1.4G    site-packages/nvidia
1.8G    site-packages/torch
1.8G    site-packages/torch/lib
```

**Comment by ngosang** [comment]
I think we should split the Docker image in 2 images: with and without cuda support.
I can open a PR but I will like to hear your opinion first.

**Comment by dingedi** [comment]
Good idea i think. Not everyone need cuda

**Comment by pierotofy** [comment]
I'm OK with that.

**Comment by Joly0** [comment]
Would it be possible to load some of that when the container starts and save it somewhere in a volume? That way those big files only get downloaded once and can be reused every time without stuffing them in the image itself and bloating it that way

**Comment by thomas-mc-work** [comment]
Hello @Joly0,

as a user I always prefer a transparent solution like the split images like suggested above. There you can see beforehand what you can expect. And you know the data transfer is done after you've downloaded the image. For me, it's rather unusual if a download starts on the first startup. Also, this wouldn't heal the problem of having too much data that is being transferred. It's just "hidden" in a delayed transfer. I hope this helps.

**Comment by Joly0** [comment]
> Hello @Joly0,
> 
> as a user I always prefer a transparent solution like the split images like suggested above. There you can see beforehand what you can expect. And you know the data transfer is done after you've downloaded the image. For me, it's rather unusual if a download starts on the first startup. Also, this wouldn't heal the problem of having too much data that is being transferred. It's just "hidden" in a delayed transfer. I hope this helps.

You might have misunderstood what i meant or maybe i wasnt clear enough. 
I am aswell for splitting the image. Though for people that want to use the nvidia image, its still absolutly useless to download 2gb of data every time the container has an update, without anything regarding the nvidia part changing. So it makes sense to have the nvidia part split into a separate dockerfile, but imho it also would make alot of sense to not download the same huge data over and over.

I understand your concern regarding downloading filea afterwards, but there is a solution to it aswell: The dockerfile should be adjusted so the download and setup of the nvidia files are in a separate RUN command. Therefore docker caches those things and only downloada them again, if they have changed in an update. Otherwise docker is smart enough to just reuse the old stuff, that hasnt been updated.

Other than that, my first idea would reduce the transparency, though this data would only needed to be downloaded once and never ever afterwards, and if i understand it correctly, this docker has to download alot of (language-)files afterwards anyway. So wouldnt interupt the user that much

**Comment by ngosang** [comment]
I also think downloading data in the entrypoint is bad idea.
* It will re-download the files in each run. It could be improved to have a persistent volume but it has to be configured too.
* The container start up time will increase.
* Some users may want to use LibreTranslate without internet connexion. There are ways to deploy containers without Internet at all.

TODO:
* Build 2 different images. One without cuda support (main image) and one with cuda support that extends the main image so we can reuse Docker layers.
* Update the docker-compose
* Update the doc
* Update the GitHub actions to build and publish both images.

I will take a look when I clear my backlog.

**Comment by ngosang** [comment]
Sorry guys but I don't have time to work on this.
* I discovered that pyTorch does not provide compiled packages without cuda/nvidia depenencies.
* We neither can delete the folder `venv/lib/python*/site-packages/nvidia`
* We can build pyTorch from source code without cuda and other parts of pyTorch required. The size reduction is phenomenal (like 1.5 GB uncompressed).

The trick is this:
* We need to install pytorch from the source code before running "pip install". The `torch` package will be already installed and it won't be downloaded.

Example (not working but you get the idea):
```
# Install system packages to build C code
RUN apt-get install -y curl cmake
# Install pyTorch dependencies in the system path (not in venv because they are not required after the package is built)
RUN pip install astunparse numpy ninja pyyaml setuptools cmake typing_extensions six requests dataclasses mkl mkl-include
# Install pyTorch in the venv
RUN set -ex \
  && export USE_CUDA=0 \
  && curl -L -o /tmp/torch.tar.gz https://github.com/pytorch/pytorch/archive/refs/tags/v1.13.1.tar.gz \
  && tar xvf /tmp/torch.tar.gz -C /tmp \
  && ./venv/bin/python /tmp/pytorch*/setup.py install
# Install babel and other requirements
# Copy /app to the final image
```

Other things:
* You can also save some size if you don't copy all files in libretranslate repository `COPY . .` I think only `libretranslate` and `scripts` folders are required.
* `docker-compose.yml` is using the .cuda image
* Rename `docker/cuda.Dockerfile` to `docker/Dockerfile.cuda` (it's more standard)

**Comment by pierotofy** [comment]
How about:

```
pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu
```

?

**Comment by ngosang** [comment]
Nice find. If you replace this lines in the Dockerfile. The uncompressed size 4.2 GB => 1.1 GB. I don't know how much will be the compressed size (what you can see in DockerHub) but it will be lower.
I didn't test it but it should work:
```
RUN ./venv/bin/pip install Babel==2.11.0 && ./venv/bin/python scripts/compile_locales.py \
  && ./venv/bin/pip install torch --extra-index-url https://download.pytorch.org/whl/cpu \
  && ./venv/bin/pip install . \
  && ./venv/bin/pip cache purge
```

Remember the other things I said in my previous post.

**Comment by gaby** [comment]
@ngosang Any updates on getting these changes merge?

**Comment by ngosang** [comment]
Sorry, I'm not using this project anymore. Anyone can take the ideas and open PRs.

**Comment by ngosang** [comment]
Why the difference in size between arm and x64?
![imagen](https://user-images.githubusercontent.com/10577978/229371986-d12da7ff-9978-413d-a6e5-aba502be31c2.png)
