### ISSUE TITLE
Word results improvement English to Spanish

### ISSUE THREAD

**Issue by inglesuniversal** [LibreTranslate/LibreTranslate#361]
Is there a place to contribute to refine some translation results... I have helped Google a lot and now it is my turn to help here.

A very simple and common way to verify the quality of a translation is by using slang instead of standard expressions.

So I checked the translation of ...

She is a very "horny" girl (into Spanish) and gave me ---> Ella es una chica muy "caliente" ... instead of ---> Ella es una chica muy "cachonda" (which is the proper slang word widely used)

If there is a panel of translators in your team, let me know how to participate. I've been in the ESL industry for over 25 years.

Best regards

**Comment by pierotofy** [comment]
Hey @inglesuniversal 👋 you can contribute suggestions on https://libretranslate.com (press the "Edit" pencil icon next to the output translation to write a suggestion).

**Comment by inglesuniversal** [comment]
Thanks for the TIP, clicked on the EDIT button but results were the same after trying on a new tab on my browser. How long does it take for the changes/suggestions to become available?

Thanks

**Comment by pierotofy** [comment]
They are not immediate; the suggestions are recorded and may be used for training future, better language models.
