### ISSUE TITLE
Problems with corrections on a self-hosted docker instance

### ISSUE THREAD

**Issue by ovizii** [LibreTranslate/LibreTranslate#363]
Clicking the “edit” icon within the translated result makes the focus jump to the original text field.

Correcting the result of the translation is basically impossible. Some other users seem to have confirmed this in the community forum. => https://community.libretranslate.com/t/frontend-problems-with-corrections-in-a-self-hosted-docker-instance

**Comment by pierotofy** [comment]
This should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/282737519cc3e74f09279be4da5197bccc8574b6 :pray: thanks for the report!
