### ISSUE TITLE
file translation fails (using docker container)

### ISSUE THREAD

**Issue by dolorosus** [LibreTranslate/LibreTranslate#376]
Trying to translate a txt file in a self hosted docker container (libretranslate/libretranslate) results in this error message:

    Could not build url for endpoint 'download_file' with values ['filename']. Did you mean 'Main app.download_file' instead?

**Comment by pierotofy** [comment]
Thanks @dolorosus :pray: this was introduced by mistake with https://github.com/LibreTranslate/LibreTranslate/commit/638d664cffdb325cfc32fc3d7333da2455c56e2f but should be fixed now.
