### ISSUE TITLE
Translate 1 word to Indonesia resulting in "login" or "sitemap"

### ISSUE THREAD

**Issue by wiryadev** [LibreTranslate/LibreTranslate#379]
As the title suggest, translating single word to Indonesia resulting in "login" or "sitemap".

Example for "login": 
https://libretranslate.com/?source=en&target=id&q=hello
https://libretranslate.com/?source=en&target=id&q=dust

Example for "sitemap": 
https://libretranslate.com/?source=en&target=id&q=here
https://libretranslate.com/?source=en&target=id&q=done

**Comment by dingedi** [comment]
This problem is more related to models and argos-translate, you can open an issue directly on the [argostranslate github](https://github.com/argosopentech/argos-translate)
