### ISSUE TITLE
pip install not possible due to OOM 

### ISSUE THREAD

**Issue by Cyborgscode** [LibreTranslate/LibreTranslate#38]
Your Build instructions require this step:

pip install -r requirements.txt

which results in : 

...
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/c7/e6/dccac76b7e825915ffb906beeba5a953597b6cfe1fe686b5276e122cb07c/numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl
Collecting torch>=1.3.0
  Downloading https://files.pythonhosted.org/packages/1d/a9/f349273a0327fdf20a73188c9c3aa7dbce68f86fad422eadd366fd2ed7a0/torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl (776.8MB)
     |███████████                     | 269.3MB 76.0MB/s eta 0:00:07ERROR: Could not install packages due to an EnvironmentError: [Errno 28] Auf dem Gerät ist kein Speicherplatz mehr verfügbar

Which has more than enough space left:  

/dev/xvda1       78G     29G   46G   39% /

Which lead to the only limiting factor on this server: /tmp/  which runs out of space, because pip downloads stuff there, instead of "./" 

After freeing up some space there, the same step failed with a "killed":

Collecting numpy
  Using cached https://files.pythonhosted.org/packages/c7/e6/dccac76b7e825915ffb906beeba5a953597b6cfe1fe686b5276e122cb07c/numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl
Collecting torch>=1.3.0
  Downloading https://files.pythonhosted.org/packages/1d/a9/f349273a0327fdf20a73188c9c3aa7dbce68f86fad422eadd366fd2ed7a0/torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl (776.8MB)
     |████████████████████████████████| 776.8MB 67.4MB/s eta 0:00:01**Getötet**

("getötet" German => "killed" ) 

because it gets killed, it doe snot remove it's tempfiles, which brings us back to step 1 in this Bugreport. 

You really need to check things BEFORE the actions starts :)

**Comment by Cyborgscode** [comment]
If i may add: as /tmp/ is a dynamic ram drive by default, the more there is added, the less actual ram is allocateable to the programs itself, which is avoidable by not downloading stuff to /tmp/ in the first place.

**Comment by PJ-Finlay** [comment]
Try `pip install -r requirements.txt --no-cache-dir`

https://stackoverflow.com/questions/62030345/pip-install-torch-killed-at-99-excessive-memory-usage

Torch is a big dependency and I had a similar issue building Snap packages with 2GB of RAM and [had to increase to 4GB](https://github.com/argosopentech/argos-translate/blob/1ae5bc9aeba89172496a09367e7e3a3c471dc5a3/README.md#build-and-install-snap-package).

**Comment by pierotofy** [comment]
@Cyborgscode if this workaround works for you would you mind adding a note in the README?
