### ISSUE TITLE
Add Kabyle language to Weblate

### ISSUE THREAD

**Issue by BoFFire** [LibreTranslate/LibreTranslate#384]
Hi,

Please add Kabyle `kab` as a new language to Weblate for localization.

Thank you !

**Comment by ZiriSut** [comment]
Hi,

Please add Kabyle kab as a new language to Weblate for localization.

Thank you !

**Comment by pierotofy** [comment]
Done! https://hosted.weblate.org/projects/libretranslate/app/kab/

**Comment by BoFFire** [comment]
Thank you @pierotofy :)
