### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [LibreTranslate/LibreTranslate#389]
https://hosted.weblate.org/projects/libretranslate/app/#information specifies AGPLv3-only,
whereas the repo has no indication in either direction.
It seems beneficial to not take contributions artificially limited in light of the possibility of deciding whether a future version being better once it exists.

**Comment by pierotofy** [comment]
Changed to AGPLv3 (or later). Thanks.

**Comment by comradekingu** [comment]
@pierotofy Might want to change https://hosted.weblate.org/projects/libretranslate/glossary/ too in
https://hosted.weblate.org/settings/libretranslate/glossary/
