### ISSUE TITLE
General issue about bad language detection (and how to possibly fix it)

### ISSUE THREAD

**Issue by schrmh** [LibreTranslate/LibreTranslate#395]
(Does address issues like https://github.com/LibreTranslate/LibreTranslate/issues/247 as well)

So, this night I tried out LibreTranslate again cause a friend said I should take a look. I found out it used polyglot (was corrected later that it now uses CLD 2 directly instead of polyglot which uses CLD2 via another library) which just performs horrible when it comes to the languages I care about (German, Japanese and English).
I then noticed that LibreTranslate used to use langdetect which was way more accurate when it came to my personal tests thus I commented on a merge request which also contains some findings so far:
https://github.com/LibreTranslate/LibreTranslate/pull/60#issuecomment-1384644446 contains my findings so far (read following comments as well there)

After this, I found out a bit more (e.g. for German and English, fasttext seems to be actually better according to graphs in https://github.com/pemistahl/lingua-py. 
And when it comes to quotes then lingua might fail https://github.com/pemistahl/lingua-py/issues/112 when it would return better results than langdetect if it was asked for each part individually) and thus I'm opening a issue to make it easier to keep an eye on that and cases which should be considered (and to attract potential contributers).

So things to do IMO:
- Replace CDL 2 with lingua-py for a quick boost in accuracy (it seems it is only worth to use CDL 2 if Mangolian is one of the languages you want to detect and the others are languages in which CDL 2 is as good as the other libraries)
- Implement fasttext as another option and bring back langdetect as well
- Give the user the choice which to use
- load-only should then really only care about selected languages if possible (I have the feeling it doesn't, looking at accuracy)
- Try to choose the library based on the load-only languages
- Try to choose the library depending on what is input (e.g. single word, sentence, sentences with words in other languages quoted like `Er sagte "わたし"`)
- Option to be deterministic if possible (e.g. langdetect provides an option like this so that it doesn't detect something as language 1 in the first try and the very same thing as language 2 in another try)

Detection might be tested by looping over words and sentences from lists from wiktionary (it provides such lists in machine-readable formats as downloads: https://en.wiktionary.org/wiki/Help:FAQ#Downloading_Wiktionary) and then checking out the cases it did not detect as expected (e.g. is there a different language with the same word or was it really just bad detection?).

More complex but since e.g. lingua supports multi language detection in mixed texts it might be worth it to consider to implement such things as well...:
- Option to enable/disable multi language detection in input
- In case multiple languages are input then consider highlighting the different parts somehow (e.g. in the GUI colors could be used)
- Option to not translate a language in a multi language text
- Option to translate to multiple targets (translate everything always to language X and Y)
- Specific language rules (when language X is detected, translate to language Y but when A is detected then to B)

**Comment by Mux199** [comment]
Hello,
Can I take this issue?

**Comment by pierotofy** [comment]
We'd love help. See #396 which has already started some work in this area.

**Comment by Tampa** [comment]
Predictably with many of the models the translations to English are a lot better than the other way around. This is a known problem for most of the translation services as well, though they have gotten better recently. I'm looking at the models and how to create them, but ML is not my area of expertise at all. Is language detection and overall translation quality something that throwing more hardware at the problem could help with? I have spare machinery that I'd happily donate to build better models for these things.

**Comment by schrmh** [comment]
@Tampa Well, I think you need both: a good set of training data as well as the machine power.
There is a section "Adding New Language Models" in the README of this project. Might be worth checking it out.

It would especially be good if a model similar to lingua-py's could be created. The problem with theirs is that it fails at detecting simple, every day common words like "hello". It excels at more complex words thus I would say in worst case we just let words with <5 chars translate by something else than lingua-py (or just hardcode the simple words it fails with)...

**Comment by Tampa** [comment]
The current models are weird in that way as well. Tried translating "hilarious" and it gave me "scary" or just "hilari". Somehow has that wrong even in longer sentences, though it normally does better with those.

I read that section, have yet to watch the attached video. It's not quite clear what's what, where the actual origin of the data is and what exactly is trained. I'll try to make sense of that, but if the actual training data is the problem then that should be the first step; finding a better source of a larger dataset for doing the training on.

The project I aim to use libretranslate for has a couple hundred users so perhaps they can be of help providing data? Or perhaps some other way to crowdsource this?

**Comment by schrmh** [comment]
@Tampa Yeah, CDL 2 is just bad but it gets at least "hello" correct. 
In fact, it is so bad (for german at least) that I just don't use LibreTranslate at all at the moment since I don't want to have yet another local copy of a multi gigabyte taking software on my machine just to be able to use lingua-py with it.

**Regarding how hundreds of users could help**:  
I guess they could especially help there (from the first post in this issue):
»Detection might be tested by looping over words and sentences from lists from wiktionary (it provides such lists in machine-readable formats as downloads: https://en.wiktionary.org/wiki/Help:FAQ#Downloading_Wiktionary) and then checking out the cases it did not detect as expected (e.g. is there a different language with the same word or was it really just bad detection?).«

Else @pierotofy might have some idea? Or @pemistahl (I know it's not really your issue but since lingua-py is considered here... it just needs some improvements)?

**Comment by Tampa** [comment]
I'm throwing feelers out for crowdsourcing datasets or anyone with some machine learning background. If the documentation could be improved to a point where I can build a pipeline from translations->dataset->training->model->deployment then I can automate a test environment crowdsourced data can be fed into.

**Comment by bruno-kakele** [comment]
+1 I also noticed that detection needs improvement! I am using LibreTranslate in my game, if you need help A/B testing with some users let me know and we can set something up (however the language coverage is mostly PT-BR, ES, EN and PL).

**Comment by pierotofy** [comment]
We now use a hybrid lingua + LexiLang (https://github.com/LibreTranslate/LexiLang) for performing language detection. :tada: 

If you find other issues with detection, feel free to open a new issue with examples of incorrect detection. :pray:

**Comment by pemistahl** [comment]
Hi @schrmh and @pierotofy, thank you for using my library Lingua in LibreTranslate. This is awesome. :-)

I just want you to know that I'm currently working on official Python bindings for the Rust implementation of Lingua. The goal is to let those bindings cover all functionality and mostly the same API as the pure Python implementation. With the official bindings you won't have to rely on badly maintained third-party bindings anymore.

If you are interested I will inform you as soon as the bindings are ready.

**Comment by pierotofy** [comment]
Oh that would be awesome @pemistahl !

**Comment by pemistahl** [comment]
@schrmh @pierotofy I released [Lingua 2.0.0](https://pypi.org/project/lingua-language-detector/) yesterday which now covers the full API of Lingua. You will probably want to replace the third-party bindings with my official ones now. If you encounter any problems with these, please let me know. Thanks.
