### ISSUE TITLE
Capitalization issues, e.g. Asian Section 

### ISSUE THREAD

**Issue by tacman** [LibreTranslate/LibreTranslate#399]
*European Archaeology Section* does not translate from English to Spanish  

![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/182fc364-118a-48ea-88f6-b7f3018473e8)

https://libretranslate.com/?source=en&target=en&q=European%2520Archaeology%2520Section

Ditto for Asian: https://libretranslate.com/?source=auto&target=en&q=Asian%2520Archaeology%2520Section

But *Archaeology Section* works fine:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/17af4b6e-15a9-4a14-93dc-f4ab61ad7e7e)

https://libretranslate.com/?source=en&target=es&q=Archaeology%2520Section

And European by itself is fine:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/35db2d48-5ba5-49ca-8272-c607a84c8037)

https://libretranslate.com/?source=en&target=es&q=European

And *Asian food* is fine:

https://libretranslate.com/?source=en&target=es&q=Asian%2520food

Asian Section is not, but Asian section is:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/3ea11ec4-ff34-4a96-ad05-f0d131dc2715)

https://libretranslate.com/?source=en&target=es&q=Asian%2520Section
![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/5ec232f8-ec5e-4e21-9449-a1153982dd49)

https://libretranslate.com/?source=en&target=es&q=Asian%2520section

European archaeology section also works fine:

![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/fbe67a98-a66d-4174-825d-b87d24374e5c)
https://libretranslate.com/?source=en&target=es&q=European%2520archaeology%2520section

But "european archaeology section" oddly produces "europeann archaeology section"
![image](https://github.com/LibreTranslate/LibreTranslate/assets/619585/af068adf-1f25-4e2f-a060-56742afd32f6)

https://libretranslate.com/?source=en&target=es&q=european%2520archaeology%2520section

So I'm guessing there are some rules about capitalization?  Or maybe it's a bug.  Regardless, I figured I'd report it. 

So my code now goes through the capitalization variations hoping that something translates. Any chance you could label this as a bug instead of an enhancement, @pierotofy  or @PJ-Finlay ?

Thanks for sharing this awesome software!

**Comment by PJ-Finlay** [comment]
I think this is the translation neural network generating a weird output not a bug with the LibreTranslate software itself. 

We get feedback like this a lot but there isn't much we can do besides trying to improve the data and models in general. Maybe we could make a reference issue or wiki on the forum to direct people to for submitting translation feedback?

https://community.libretranslate.com/t/submitting-feedback-for-individual-translations/515
