### ISSUE TITLE
[Feature request] Configure the translator using the get method

### ISSUE THREAD

**Issue by wuniversales** [LibreTranslate/LibreTranslate#40]
Example: 
`https://libretranslate.com/?lang=auto&translate=es&text=hi`

Something like that, it would be good to be able to use it from other projects.

**Comment by pierotofy** [comment]
Hey @wuniversales :hand: would you be interested in contributing a PR for this?

**Comment by wuniversales** [comment]
I don't really have experience in pyton, so I don't know how to get, if it would be with pure js... I don't think it's a good idea to do that.

**Comment by Kershi23** [comment]
No need Pyton
