### ISSUE TITLE
Spell translated words in one's native characters

### ISSUE THREAD

**Issue by tsjnachos117** [LibreTranslate/LibreTranslate#404]
Let me start off by saying I speak English, and only understand the English alphabet. That said, I do like to occasionally translate random words to Japanese (mostly for fun). Unfortunately for me, LibreTranslate only prints the translations in Japanese characters, which I don't have the skills to read. (If I did, I probably wouldn't need to use a site like this to do the translation in the first place.) Since I speak English, I would appreciate the translations to be spelled with English characters. (Google translate does both Japanese AND English characters, making it a good learning platfrom.)

PS:
(Quote is from the template)

`For feature requests, please open pull requests directly! We accept all kinds of contributions. If you don't know how to code, you can still provide feedback, but please offer to contribute something (how are you going to help the project develop the feature?)`

As a non-programmer, is there really anything I can do? Perhaps I can test any new features added?

**Comment by pierotofy** [comment]
Testing, participating in the forum at https://community.libretranslate.com, reporting bugs, helping translate the UI (https://hosted.weblate.org/projects/libretranslate/app/) are all ways to help the project that require no coding experience.
