### ISSUE TITLE
Can not translate from English to Catalan 

### ISSUE THREAD

**Issue by tsdgeos** [LibreTranslate/LibreTranslate#405]
Interestingly one can from Catalan to English?

https://libretranslate.com/?source=ca&target=en&q=Hola%2520com%2520est%25C3%25A0s%3F <- works

https://libretranslate.com/?source=en&target=ca&q=Hello%2520how%2520are%2520you%3F <- does not work

**Comment by pierotofy** [comment]
Works now! https://libretranslate.com/?source=en&target=ca&q=Hello+how+are+you%3F

Thanks for the report. :pray:
