### ISSUE TITLE
Please update Github repo files with last changes made on Weblate for Russian

### ISSUE THREAD

**Issue by Blueberryy** [LibreTranslate/LibreTranslate#413]
I just fixed tons of things translated by robot so i hope that you will add russian as choosable language :p

**Comment by Blueberryy** [comment]
> Thanks @Blueberryy ! We will update it in the upcoming days. Would you say the Russian translation is now complete and accurate?

I can tell that it's nearly complete. Need to test how it will look on website and polish some places if will need to

**Comment by pierotofy** [comment]
Changes are now committed (and also available on https://ru.libretranslate.com/ ). :tada:

**Comment by Blueberryy** [comment]
Nice! just made few corrections in translation so it should be all good now
