### ISSUE TITLE
Chinese translation is very bad

### ISSUE THREAD

**Issue by martjay** [LibreTranslate/LibreTranslate#414]
Completely unintelligible, not as easy to understand as google

**Comment by tp1415926535** [comment]
Agreed, it seems like there are problems with even basic word translations.
Input “hello” it return the "background" mean. Puzzling.

**Comment by BackMountainDevil** [comment]
Agreed. hello's zh is not "背 景", it should be "你好".  And input "hi", got "hi"... it should be "你好" too.

**Comment by pierotofy** [comment]
I've uploaded a new Chinese <=> English model on https://libretranslate.com:

`hello` => `哈啰`
`Kyriakos Pittakis (1798–1863) was a Greek archaeologist. The first Greek to serve as the head of the country's archaeological service, he carried out the conservation and restoration of monuments on the Acropolis of Athens. ` => `克里亚科斯·皮特塔基斯(1798–1863)是希腊考古学家. 第一位出任国家考古事业负责人的希腊人,他开展了雅典雅典雅典雅典会所遗迹的保护与修复.`

**Comment by pierotofy** [comment]
And we now have Chinese traditional as well.

https://community.libretranslate.com/t/opus-mt-language-models-port-thread/757/2

For future issues about Chinese, please open a new issue with examples of input <=> result vs. expected :pray:
