### ISSUE TITLE
Intel minimum requirements error when attempting translation

### ISSUE THREAD

**Issue by rbsam176** [LibreTranslate/LibreTranslate#417]
I'm getting the following error:

```
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```

once I've started the LibreTranslate server on port 5000 and then type in anything in the browser to start a translation. To be clear, the server starts fine and the web interface loads, this error only shows once text has been entered to start a translation and it appears in the terminal.

**My setup:**
Operating system: MacOS High Sierra 10.13.6 (I know it's old)
Processor: 2.4 GHz Intel Core 2 Duo
Model: Mac mini (Mid 2010)

I'm guessing it's due to the age of the machine - is there any way to make it compatible? Do I need to install an older version of LibreTranslate perhaps?

**Comment by TheTakylo** [comment]
it comes more from [argos-translate](https://github.com/argosopentech/argos-translate) or [CTranslate2](https://github.com/OpenNMT/CTranslate2) requirements I think

maybe @PJ-Finlay know ?

**Comment by PJ-Finlay** [comment]
I think this is coming from CTranslate2.

Looking at the [docs](https://opennmt.net/CTranslate2/hardware_support.html) it says:
> CPU x86-64 processors supporting at least SSE 4.1

I'm guessing CPUs this old aren't supported.

@guillaumekln do you know?

**Comment by artenax** [comment]
torch and CTranslate2 require AVX/SSE4. 
These versions don't have these requirements:

python 3.8.20
torch 1.8.1+cpu
ctranslate2 3.20.0 [(recompiled)](https://opennmt.net/CTranslate2/installation.html) **
libretranslate 1.5.1
stanza 1.1.1
argostranslate 1.9.1

** LDFLAGS='-Wl,-rpath,/opt/python3/lib' cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/python3 -DWITH_MKL=OFF -DENABLE_CPU_DISPATCH=ON -DOPENMP_RUNTIME=COMP -DWITH_OPENBLAS=ON
cd python
python3 ./setup.py bdist_wheel
pip3 install dist/*.whl

It works with the [latest models](https://github.com/argosopentech/argospm-index/blob/main/index.json).
