### ISSUE TITLE
Where is Catalian on Weblate project?

### ISSUE THREAD

**Issue by Blueberryy** [LibreTranslate/LibreTranslate#418]
can't find this language but it's on website

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by Blueberryy** [comment]
it should be a bug because it's not added to translation file
