### ISSUE TITLE
Error when translating too many words

### ISSUE THREAD

**Issue by iacore** [LibreTranslate/LibreTranslate#437]
This is a problem of https://libretranslate.com/

When pasting too much text into the translate box:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/74560659/8efea91d-9f79-4ce9-9593-cf9b684b6683)

When pasting less text into the translate box:
![image](https://github.com/LibreTranslate/LibreTranslate/assets/74560659/49e3c289-0f5f-4920-b864-7cf62e392b3d)

**Comment by pierotofy** [comment]
There's a limit of 2,000 characters on libretranslate.com

**Comment by iacore** [comment]
The whole web page turns to that, instead of showing error in the UI.
