### ISSUE TITLE
model error when run.bat or docker run

### ISSUE THREAD

**Issue by mohammedalsayegh** [LibreTranslate/LibreTranslate#441]
When run `docker run -ti --rm -p 5000:5000 libretranslate/libretranslate`

I am getting the fallowing error:
```
Updating language models
Found 60 models
Downloading Arabic → English (1.0) ...
(URLError(gaierror(-2, 'Name or service not known')),)
(URLError(gaierror(-2, 'Name or service not known')),)
(URLError(gaierror(-2, 'Name or service not known')),)
(URLError(gaierror(-2, 'Name or service not known')),)
Cannot update models (normal if you're offline): Download failed for Arabic → English
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 156, in create_app
    language_target_fallback = languages[0]
IndexError: list index out of range
```

**Comment by Glifaus** [comment]
I have same error running .run.sh on Mac M1: 
 ./run.sh
Checking for docker...   found
Updating language models
Found 60 models
Downloading Arabic → English (1.0) ...
(URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')),)
(URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')),)
(URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')),)
(URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')),)
Cannot update models (normal if you're offline): Download failed for Arabic → English
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 156, in create_app
    language_target_fallback = languages[0]
IndexError: list index out of range

**Comment by mohammedalsayegh** [comment]
A broken url link model dependency appears to be causing Docker launches to fail, but I did not investigate further

**Comment by BigKongfuPanda** [comment]
I am getting the same error when running ./run.sh on Mac M2:
`Checking for docker...   found
Unable to find image 'libretranslate/libretranslate:latest' locally
latest: Pulling from libretranslate/libretranslate
fcdb9667c46b: Pull complete 
93a672802593: Pull complete 
8dcaf4f41922: Pull complete 
3fdc970d6941: Pull complete 
5e42bc20b98e: Pull complete 
bcd7a9bd38e4: Pull complete 
7f32767bd1c8: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:bb6609bf6541b00a876e8ea4ce6a0f7e7849ac72c0f004d6acf2d2b482a65dda
Status: Downloaded newer image for libretranslate/libretranslate:latest
Updating language models
(URLError(OSError(99, 'Cannot assign requested address')),)
Cannot update models (normal if you're offline): Local package index not found, use package.update_package_index() to load it
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 189, in main
    app = create_app(args)
  File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 160, in create_app
    language_target_fallback = languages[1] if len(languages) >= 2 else languages[0]
IndexError: list index out of range`
