### ISSUE TITLE
Add Serbian language to Weblate

### ISSUE THREAD

**Issue by ZEROF** [LibreTranslate/LibreTranslate#448]
Hi,

Can you add Serbian. ISO code is SR, but I need two templates I think (https://github.com/moment/moment/issues/3899#issuecomment-293442214). I can provide cyrillic and latin version sr-latn and sr-cyrl. To make small contribution to project of course, even that language is not included for translation and we asked long time ago :(. 

Thanks

**Comment by pierotofy** [comment]
Hi @ZEROF :wave: there should be an option to add a new language directly from Weblate?

**Comment by ZEROF** [comment]
> 

Yes, I would if that wasn't blocked and I have account.

**Comment by pierotofy** [comment]
Mm, strange. Do you get an error if you access https://hosted.weblate.org/new-lang/libretranslate/app/ ?

Can you post a screenshot?
