### ISSUE TITLE
libretranslate forum is not working

### ISSUE THREAD

**Issue by micuentadecasa** [LibreTranslate/LibreTranslate#456]
sorry to post this here, I know that the rule says to go to the forum, but I tried to register myself and I'm not receiving the confirmation email and I cannot use the forum.

Regards.

**Comment by pierotofy** [comment]
Hi @micuentadecasa have you checked the spam folder?

If the confirmation email is not there, let me know your username, I'll manually activate your account.

**Comment by micuentadecasa** [comment]
thanks Piero, my account is micuentadecasa ,and my email
***@***.***

**Comment by pierotofy** [comment]
👍 I've activated your account, so you should now be able to log-in.

**Comment by micuentadecasa** [comment]
Many thanks Piero, appreciate it.

I post a question about making libretranslate offline
https://community.libretranslate.com/t/offline-setup-docker-version/654

Regards.
