### ISSUE TITLE
salad salad salad salad salad salad salad salad

### ISSUE THREAD

**Issue by fdelapena** [LibreTranslate/LibreTranslate#46]
salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad sala salad salad salad salad salad sala salad salad salad salad salad salad salad salad salad sala salad salad salad salad salad salad salad salad salad salad salad salad sala salad salad salad sala salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad salad sala salad salad salad salad salad salad salad salad salad salad salad sala sala sala sala

![Captura de pantalla de 2021-02-18 18-45-47](https://user-images.githubusercontent.com/174885/108440874-92593200-7219-11eb-964f-26e52fd94689.png)

**Comment by randallmoraes** [comment]
salad ?

**Comment by PJ-Finlay** [comment]
Looks like it likes salad.

This is an Argos Translate issue. I reproduced it and the sentence boundary detection and tokenization look fine. Argos Translate uses a Transformer as its sequence to sequence model. The model is a black box that can sometimes have weird outputs. If you post on the [OpenNMT forum](https://forum.opennmt.net/) you might get a better answer. The PyTorch port for the training scripts is almost done which will have a larger model and more training resources but I'm not sure when an updated Spanish model will get trained. The new model will likely fix this specific issue and hopefully have fewer similar ones.

![image](https://user-images.githubusercontent.com/13067016/108448820-0b5f8600-7228-11eb-8f07-be27e2990c2f.png)

**Comment by fdelapena** [comment]
Thanks, I'll try posting about this there.
As a remark, it seems the text output in the Argos Translate you shown, it looks slightly different. Note the "sala sala sala sala sala" (without d) is not the same count and positioning. I guess the training data was not the same.

**Comment by PJ-Finlay** [comment]
In general [I don't think Argos Translate has deterministic translations](https://github.com/argosopentech/argos-translate/issues/4) the model itself was only trained once but for some reason sometimes comes up with different results. Based on the [CTranslate Python docs](https://github.com/OpenNMT/CTranslate2/blob/master/docs/python.md) it doesn't look like CTranslate supports the `lock_ngram_repeat` param they're talking about in the linked forum post.

**Comment by guillaumekln** [comment]
The training data mostly contains full sentences. So the model is good at translating sentences. But here the input is a single word which is a different task. If you want the model to perform well on these inputs, you should add such examples in the training data.

(I'm the author of CTranslate2. Feel free to tag me if you have any questions or issues. We are here to help.)

**Comment by pierotofy** [comment]
lol, I had a giggle at this :)

Hey @guillaumekln :hand: glad to have you here! CTranslate2 is pretty amazing.

**Comment by PJ-Finlay** [comment]
I added a [Wiktionary scraping script](https://github.com/argosopentech/onmt-models/commit/7cc353edb2a89f5fa9764dbb589e0ae3d5f622d7) so hopefully future models will do this better.

**Comment by bruno-kakele** [comment]
Hi @PJ-Finlay , sorry to tag you here, but for some reason my post was flagged as spam in the community forums: https://community.libretranslate.com/t/odd-translation-behavior-repeating-words/827

If I understand correctly, I need to release a more recent model for a language that includes the wiktionary data? How do I know if a language uses the Wiktextract data? (Based on this: [Argos Open Tech](https://www.argosopentech.com/argospm/index/) , I cannot tell). The [data-index.json](https://github.com/argosopentech/argos-train/blob/master/data-index.json) seems to be outdated (can't find some languages there).

Thanks in advance
