### ISSUE TITLE
Updated k8s deployment file

### ISSUE THREAD

**Issue by rasos** [LibreTranslate/LibreTranslate#464]
When deploying LibreTranslate on a kubernetes cluster and following the [medium article](https://jmrobles.medium.com/libretranslate-your-own-translation-service-on-kubernetes-b46c3e1af630) I found some issues with api versions. 

Here is a k8s file which works on an up-to-date kubernetes cluster. It allows to set an api key instead of basic auth. Feel free to replace the link on the Readme.md  https://git.fairkom.net/emb/displ.eu/language-tools/-/snippets/796

Or should I could contribute a k8s.yaml with more generic placeholders for namespace and domain ?

**Comment by pierotofy** [comment]
A contribution for better Kubernetes support would be most welcome!

**Comment by rasos** [comment]
k8s.yaml provided by https://github.com/LibreTranslate/LibreTranslate/pull/465
