### ISSUE TITLE
libretranslate_http_requests_in_flight metric does not decrement on exceptions

### ISSUE THREAD

**Issue by bruno-kakele** [LibreTranslate/LibreTranslate#480]
Not sure if this was by design, but shouldn't it be decrement on exceptions as well?

https://github.com/LibreTranslate/LibreTranslate/blob/3eea9efc15509c45cb8dbc527c9e6d85c1b98fa8/libretranslate/app.py#L296C41-L296C41

Thanks

**Comment by pierotofy** [comment]
In Python `finally` will always execute, even on exceptions. So yes it is decremented as well.

**Comment by bruno-kakele** [comment]
You are right, sorry, I am not very familiar with Python.

However, I believe there is something wrong with the gauge on my servers. I have 4 servers running it, and the gauge seems to be fixed at a minimum value (never going below a certain point):

![Screenshot from 2023-08-10 10-18-02](https://github.com/LibreTranslate/LibreTranslate/assets/56004875/d15d5e0b-f423-41dd-be65-2fb0ae7cf19e)

Any ideas on what am I missing? Thank you

**Comment by pierotofy** [comment]
Mmm, that's strange. I wouldn't discount a possible issue with LibreTranslate elsewhere in the codebase, but nothing in particular comes to mind. I'll keep this open in case this is a bug.

**Comment by bruno-kakele** [comment]
After upgrading from 1.3 to 1.5, I don't see this problem anymore! Closing as not reproducible, if it happens again I will re-open it. Thank you!

![image](https://github.com/LibreTranslate/LibreTranslate/assets/56004875/60f7d860-11df-4213-afd8-779812b9e5c3)
