### ISSUE TITLE
Document how to mark a phrase as "do not translate"

### ISSUE THREAD

**Issue by tacman** [LibreTranslate/LibreTranslate#484]
>> Please do NOT ask question about LibreTranslate here! We have a forum at https://community.libretranslate.com for questions.

I've registered but never received an email to confirm my account.  I've done this a few times, and of course have checked my spam folder.  Of course I'd prefer to ask my question there.

Is there a way to mark text that is not to be translated?  E.g. "His name was [Roger Stone]", so that Stone doesn't come out as Piedra.

Similarly, I can't find any any documentation on Suggestions that indicated if it happens as within the text, or only an exact match.

That is, to translate "My name is " and I want the Spanish to be "Me llamo" (not "mi nombre es"), but when I send in "My name is Fred", will it come out with "Me llamo Fred" (that is, it works like translation memory for words/phrases within the text) or is it only an exact mache of the text to be translated.

Again, I'd be happy to post in the forum, can someone help get me registered there?  

Gracias.

**Comment by pierotofy** [comment]
I've activated your account on the community forum. :+1: Can you re-post there? :pray:
