### ISSUE TITLE
(URLError(ConnectionRefusedError(111, 'Connection refused')),)

### ISSUE THREAD

**Issue by sunwoo1524** [LibreTranslate/LibreTranslate#486]
****************************************
Please do NOT ask question about LibreTranslate here! We have a forum at https://community.libretranslate.com for questions.

Please open an issue only to report faults and bugs.

For feature requests, please open pull requests directly! We accept all kinds of contributions. If you don't know how to code, you can still provide feedback, but please offer to contribute something (how are you going to help the project develop the feature?)

Remove these lines after reading it
****************************************
I had been setting up libre translate, and there was an error when I put `libretranslate`.
```
Updating language models
Found 60 models
Downloading Arabic → English (1.0) ...
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
(URLError(ConnectionRefusedError(111, 'Connection refused')),)
Cannot update models (normal if you're offline): Download failed for Arabic → En  glish
Traceback (most recent call last):
  File "/home/sunwoo1524/libretranslate/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/home/sunwoo1524/libretranslate/lib/python3.9/site-packages/libretransla  te/main.py", line 189, in main
    app = create_app(args)
  File "/home/sunwoo1524/libretranslate/lib/python3.9/site-packages/libretransla  te/app.py", line 156, in create_app
    language_target_fallback = languages[0]
IndexError: list index out of range
```
I searched this, but I couldn't find the answer of that.
Please help me!

**Comment by PJ-Finlay** [comment]
https://community.libretranslate.com/t/problem-with-starting-in-docker/679

**Comment by etlweather** [comment]
Essentially, same as https://github.com/LibreTranslate/LibreTranslate/issues/609
