### ISSUE TITLE
Send corretions with out a API key

### ISSUE THREAD

**Issue by www2000** [LibreTranslate/LibreTranslate#490]
Hi i wand to send corrections to the server but when i sent the server ask for a api key
error:
`Visit https://portal.libretranslate.com to get an API key`
i like there an option for a free api key for sending corrections or a with sending corrections with out a key

**Comment by pierotofy** [comment]
Mm, technically we should allow suggestions to be sent without an API key, so this is probably a bug.

**Comment by www2000** [comment]
Thanks.
For context i use the online translator at https://libretranslate.com/ for doing this.

**Comment by argosopentech** [comment]
I can't get the suggest endpoint to work at all, either at libretranslate.com or locally. 

```
#!/bin/bash

# Written by ChatGPT

# Define the URL of the LibreTranslate suggest endpoint
URL="http://127.0.0.1:5000/"

# Define your input parameters
Q="YourOriginalTextHere"
S="YourSuggestedTranslationHere"
SOURCE="en"
TARGET="es"

# If you have an API key, include it here
API_KEY="YourApiKeyHere"

# Build the JSON payload
PAYLOAD='{
  "q": "'"$Q"'",
  "s": "'"$S"'",
  "source": "'"$SOURCE"'",
  "target": "'"$TARGET"'"
}'

# Send the POST request using curl
curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$URL"

# If you have an API key, you can include it as a header like this:
# curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $API_KEY" -d "$PAYLOAD" "$URL"
```

```
$ sh ltsuggest.sh 
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by PJ-Finlay** [comment]
I wrote a [Python script to submit LibreTranslate suggestions](https://github.com/argosopentech/LTSuggest) to test this. 

I wasn't able to recreate this locally. When I run LibreTranslate with this configuration the suggest endpoint works:
```
python main.py --suggestions --api-keys --req-limit 10
```
```
$ python demo.py 
Status code: 200
{'success': True}

```

However, I see the same bug when trying to connect to LibreTranslate.com:
```
$ python demo.py 
Status code: 400
{'error': 'Visit https://portal.libretranslate.com to get an API key'}
```

Based on my reading of the code it seems like you should be able to make suggest requests as long as your IP address isn't over the request limit. I can make translate requests to LibreTranslate.com so I don't think I'm over the limit and don't know what the problem is.

**Comment by PJ-Finlay** [comment]
I see there's a recent commit touching this code so it's possible I'm running a newer version than LibreTranslate.com:
https://github.com/LibreTranslate/LibreTranslate/commit/cb11dfc6b13ed05eda0365e76a1adf1e38eef228

**Comment by www2000** [comment]
@PJ-Finlay what i understand of the code is for upload json.
The problem is that there is a api key need for sending a correction using the api or the website.
I have no problem with a free api key that is limit for sending corrections.
But this limit the current grow of LibreTranslate.
