### ISSUE TITLE
Dropdown text color bug

### ISSUE THREAD

**Issue by Blueberryy** [LibreTranslate/LibreTranslate#491]
Text is white on white background which makes it impossible to see, you can see text only when you hover on it.
![image](https://github.com/LibreTranslate/LibreTranslate/assets/36592509/46c8f7ba-fd97-4e38-9245-7a3af1cc9f3b)
Using Opera GX browser.

**Comment by PJ-Finlay** [comment]
I'm guessing this commit is the cause:
https://github.com/LibreTranslate/LibreTranslate/commit/5e6d1642e3310fd24a5ac84e39015a776b2d7117

The are other recent UI commits I see thiat might have caused this issue:
- https://github.com/LibreTranslate/LibreTranslate/commit/d4071e8a0244e84ba13ace095ee599cdd59b2386
- https://github.com/LibreTranslate/LibreTranslate/commit/193b6284d43314cb6980386c7631f58cc544bc25
- https://github.com/LibreTranslate/LibreTranslate/commit/1c3f3e56962591cb25ba54e7e427cd27b6fffd87
- https://github.com/LibreTranslate/LibreTranslate/commit/88021880cd03bd142d60dfe6afaf6de7807fde0d

**Comment by argosopentech** [comment]
I was able to reproduce this bug in Brave Browser and have a fix here:
https://github.com/LibreTranslate/LibreTranslate/pull/493
