### ISSUE TITLE
local hosted server API keys not working

### ISSUE THREAD

**Issue by snagi12** [LibreTranslate/LibreTranslate#492]
I am not sure if this is a bug or what but every API key generated via ltmanage command locally on our server for selfhosted projects says invalid key.
LibreTranslate is launched as a service on CentOS 7 with the --ssl --api-keys  commands
we even tried adding  --api-keys-db-path=/home/admin/web/"webdomain"/public_html/LibreTranslate/db/api_keys.db command as well

API works fine without the --api-keys commands but we can't limit since local API keys are not valid.

**Comment by pierotofy** [comment]
I'm guessing this is *probably* not a bug; maybe you're not adding the keys correctly? 

Let's move the conversation over to https://community.libretranslate.com 🙏 for all setup questions.
