### ISSUE TITLE
Slow translation of selected words from English to Chinese

### ISSUE THREAD

**Issue by ssworldss** [LibreTranslate/LibreTranslate#497]
We have observed that few of the like create etc takes time to translate when translated from English to Chinese , is there any specific reason for it? 
Can it be trained to so that next time it wont take time?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
