### ISSUE TITLE
Greek translation fails [possible bug]

### ISSUE THREAD

**Issue by alam-R** [LibreTranslate/LibreTranslate#499]
Try the below request:
```
{
    "q": "το λογότυπο με τον πράσινο βάτραχο σε συσκευασία τροφίμων δεν υποδηλώνει ότι περιέχουν ατραζίνη",
    "source": "el",
    "target": "en",
    "format": "text"
}
```
The response is totally non sense:
```
{
    "translatedText": "send your inquiry directly to us"
}
```

But if you add '"' in the end:
```
{
    "q": "το λογότυπο με τον πράσινο βάτραχο σε συσκευασία τροφίμων δεν υποδηλώνει ότι περιέχουν ατραζίνη\"",
    "source": "el",
    "target": "en",
    "format": "text"
}
```
you get:
```
{
    "translatedText": "the logo with green jars in food packaging does not suggest that they contain arasene\""
}
```

**Comment by alam-R** [comment]
Furthemore we have found that adding **"** in front and in the end of the q significantly improves the translation, even though the model needs improvement in case of Greek language.

eg.
```
"q": "Ψευδοεπιστημονικοί ισχυρισμοί για τους υποτιθέμενους κινδύνους της υιοθεσίας παιδιών από ομόφυλα ζευγάρια",
returns
"translatedText": "We use cookies to ensure that we give you the best experience on our website. If you continue to use this site we will assume that you are happy with it.Ok"
```

while

```
"q": "\"Ψευδοεπιστημονικοί ισχυρισμοί για τους υποτιθέμενους κινδύνους της υιοθεσίας παιδιών από ομόφυλα ζευγάρια\"",
returns
"translatedText": "“Professional claims for the alleged dangers of the child’s decryption from a couple”"
```

**Comment by pierotofy** [comment]
https://libretranslate.com/?source=auto&target=en&q=%CF%84%CE%BF+%CE%BB%CE%BF%CE%B3%CF%8C%CF%84%CF%85%CF%80%CE%BF+%CE%BC%CE%B5+%CF%84%CE%BF%CE%BD+%CF%80%CF%81%CE%AC%CF%83%CE%B9%CE%BD%CE%BF+%CE%B2%CE%AC%CF%84%CF%81%CE%B1%CF%87%CE%BF+%CF%83%CE%B5+%CF%83%CF%85%CF%83%CE%BA%CE%B5%CF%85%CE%B1%CF%83%CE%AF%CE%B1+%CF%84%CF%81%CE%BF%CF%86%CE%AF%CE%BC%CF%89%CE%BD+%CE%B4%CE%B5%CE%BD+%CF%85%CF%80%CE%BF%CE%B4%CE%B7%CE%BB%CF%8E%CE%BD%CE%B5%CE%B9+%CF%8C%CF%84%CE%B9+%CF%80%CE%B5%CF%81%CE%B9%CE%AD%CF%87%CE%BF%CF%85%CE%BD+%CE%B1%CF%84%CF%81%CE%B1%CE%B6%CE%AF%CE%BD%CE%B7

New greek model is available from https://community.libretranslate.com/t/opus-mt-language-models-port-thread/757/2 hopefully it will become available soon in the argos-index. :+1: 

Thanks for the report!
