### ISSUE TITLE
French version of the website is not working

### ISSUE THREAD

**Issue by idotj** [LibreTranslate/LibreTranslate#509]
Changing the website language to French redirects to:
[https://fr.libretranslate.com/](https://fr.libretranslate.com/)
but throws a "Server Not Found" page.

![image](https://github.com/LibreTranslate/LibreTranslate/assets/6554216/33aa8125-03db-440e-bf47-8d41513131cc)

No idea if it's just a server config problem or the french version is not available/finished yet (in that case better to hide the option from the drop-down list).

**Comment by pierotofy** [comment]
Thanks @idotj , a DNS entry was missing. It should be fixed and online now :+1:
