### ISSUE TITLE
Set default colors

### ISSUE THREAD

**Issue by tastytea** [LibreTranslate/LibreTranslate#52]
I have set the default colors in my browser to BG: #131315 and FG: #E1E1E1.¹
This is how <https://libretranslate.com/> looks for me: ![screenshot_2021-02-26T23:16:22](https://user-images.githubusercontent.com/3681516/109361243-e6eb5580-7888-11eb-8f0a-79daa05f001b.png).

When you specify a background color, please specify a text color as well. When you specify a text color, please specify a background color as well. 

¹ <https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_change-font-color>

**Comment by pierotofy** [comment]
Hey @tastytea :hand: we'd welcome improvements to the interface (interested in making a contribution?)

**Comment by tastytea** [comment]
@pierotofy No. Your CSS files are huge and complicated (and on top of that “minified”) and I'd have to spend a considerable amount of time to understand what's going on. It'd be much quicker if the person that set up the theme would fix it, since they presumably know how all the stuff interacts and where the fix is needed.

**Comment by pierotofy** [comment]
I'm sorry to hear that :( unfortunately I won't have the time to add this myself in the short term. Perhaps somebody else in the future will jump in and add it.

**Comment by idotj** [comment]
I have been working in a new UI to improve the translation. I got all working on my local branch, but no access to push the changes. I uploaded the files needed here:
http://box.idotj.com/box/LibreTranslate.zip

**Comment by pierotofy** [comment]
Hey @idotj you need to first fork the repository on GitHub, then you can push to your repo's fork local branch. Then you can consider opening a pull request.

**Comment by idotj** [comment]
> Hey @idotj you need to first fork the repository on GitHub, then you can push to your repo's fork local branch. Then you can consider opening a pull request.

Thanks @pierotofy I updated my comment 👍
