### ISSUE TITLE
UX Web interface - Difficult to use on a smartphone

### ISSUE THREAD

**Issue by skytux** [LibreTranslate/LibreTranslate#521]
![Screenshot_20231024-000235_Samsung Internet](https://github.com/LibreTranslate/LibreTranslate/assets/3109677/b74092be-85b6-4f9e-901e-5dd269fee2a6)

It would be more accessible to read if the translation appears below but not on the side from a smartphone.

It's a no for me to use in this state.

**Comment by pierotofy** [comment]
Thanks, this should be fixed/improved with https://github.com/LibreTranslate/LibreTranslate/commit/001a870fbd29e0678210b7c53c6049fe7eb6a191 :clinking_glasses:
