### ISSUE TITLE
Can't translate to some languages on localhost

### ISSUE THREAD

**Issue by lucaspierre1** [LibreTranslate/LibreTranslate#523]
Request:
```javascript
const res = await fetch("http://127.0.0.1:5000/translate", {
	method: "POST",
	body: JSON.stringify({
		q: "Hello ",
		source: "en",
		target: "bg",
		format: "text",
		api_key: ""
	}),
	headers: { "Content-Type": "application/json" }
});

console.log(await res.json());
```

Error message:
Cannot translate text: Unsupported model binary version. This executable supports models with binary version v5 or below, but the model has binary version v6. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)

**Comment by pierotofy** [comment]
Make sure you're running the latest version of LibreTranslate (you might need to update it).

**Comment by lucaspierre1** [comment]
> Make sure you're running the latest version of LibreTranslate (you might need to update it).

To update I just need to run `pip install -U libretranslate` ?
If yes, I already did and still doesn't work.

**Comment by pierotofy** [comment]
1. Make sure you're starting from a fresh virtualenv
2. If this still happens, please share details about your particular setup, what machine, operating system, python version, etc.

**Comment by lucaspierre1** [comment]
> 1. Make sure you're starting from a fresh virtualenv
> 
>     2. If this still happens, please share details about your particular setup, what machine, operating system, python version, etc.

I uninstalled all my libraries from my user and virtual environment and reinstalled them. It's working now, thank you!
