### ISSUE TITLE
Dockerfile not working on fly.io server

### ISSUE THREAD

**Issue by stephan-fischer** [LibreTranslate/LibreTranslate#531]
I haved installed the docker on a fly.io server with the global docker file:
` fly deploy -i libretranslate/libretranslate`
and before i increased  the memory to 512 mb:
`fly machine update -a libre-translate --vm-memory 512M XXXXXX`

but i got always this error:
`2023-11-06T09:38:17.035 proxy[32873d2f694e28] ams [error] instance refused connection. is your app listening on 0.0.0.0:5000? make sure it is not only listening on 127.0.0.1 (hint: look at your startup logs, servers often print the address they are listening on)`

Any suggestion for it? Maybe the Dockerfile is not right?

**Comment by gedw99** [comment]
I also tried to run this on fly.io with and without gpu and got the same errors.

It’s a shame that fly.io is not working / supported. Fly will auto scale up and down so it’s a highly cost efficient way to host
