### ISSUE TITLE
Double translates texts

### ISSUE THREAD

**Issue by By-PorfecTo** [LibreTranslate/LibreTranslate#544]
double translates some texts

![ScreenShot_20231123160822](https://github.com/LibreTranslate/LibreTranslate/assets/92230690/ffb679d7-82e3-4066-b416-1553d0c961aa)

I also tried it at https://libretranslate.com/ and the result is the same.

**Comment by pierotofy** [comment]
Thanks for the report @By-PorfecTo :pray: this should now be fixed with the latest version.
