### ISSUE TITLE
serious translation fault

### ISSUE THREAD

**Issue by Paroryx** [LibreTranslate/LibreTranslate#548]
![translation-fail](https://github.com/LibreTranslate/LibreTranslate/assets/93038439/01c41795-aa02-4a51-bc1c-f53def2e1b63)
``Irish -> German``
I used LibreTranslate for my school project, and it almost tended up in a fatal situation xD

**Comment by rffontenelle** [comment]
Have you tried to do the same translation request in libretranslate.com page and suggest the correct translation?

**Comment by chris-devel0per** [comment]
I'm in the same translation, on my local and on the online (https://libretranslate.com/?source=ga&target=de&q=Fóram)! No Irish skills here, but I played around with some translation tools. The Irish to German one is totally off. Any ideas on fixing it?

**Comment by rffontenelle** [comment]
Quoting a [reply in LibreTranslate forums](https://community.libretranslate.com/t/how-to-help-libretranslate-as-a-user-not-developer/775):

> _While models are pre-trained, you can submit suggestions on [https://libretranslate.com](https://libretranslate.com) by pressing the “Edit” button (pencil icon) if a translation is wrong. The suggestions are not immediately taken in consideration, but they might be included in a future language model update._

**Comment by PJ-Finlay** [comment]
@rffontenelle is right. The best way to help the devs if you find an incorrect translation is to use the edit button on https://LibreTranslate.com

![LibreTranslate Edit Translation](https://github.com/LibreTranslate/LibreTranslate/assets/13067016/75686efa-36c1-480b-bd18-2d4368c2e390)

I submitted this one for you:

![image](https://github.com/LibreTranslate/LibreTranslate/assets/13067016/548eb941-7ac2-4ca2-b7e9-e410f98b9ea4)


Thanks for the feedback! Hopefully the faulty translation didn't get you into any trouble haha
