### ISSUE TITLE
Output duplication

### ISSUE THREAD

**Issue by LevelWilson** [LibreTranslate/LibreTranslate#549]
<img width="1275" alt="Screenshot 2023-12-03 at 7 21 01 PM" src="https://github.com/LibreTranslate/LibreTranslate/assets/96966217/c96550f4-940b-40e8-8d90-45399216f128">

**Comment by kak-smko** [comment]
same issue
![Screenshot 2023-12-09 103458](https://github.com/LibreTranslate/LibreTranslate/assets/38558807/040f6c4e-91b8-4039-b725-06c300645fba)

**Comment by pierotofy** [comment]
Thanks for the reports! This should now be fixed :pray:
