### ISSUE TITLE
A request - not an issue

### ISSUE THREAD

**Issue by ineuw** [LibreTranslate/LibreTranslate#550]
Sorry for posting this, but I don't know how to get in touch with the administrators of https://community.libretranslate.com. Their new user registration is broken. I failed to receive their confirmation email, after trying daily for the past week. Thanks.

**Comment by ineuw** [comment]
Dear automated script,

Please let human eyes read it, before closing.

You are no help.

**Comment by pierotofy** [comment]
I've manually activated your account on the forum @ineuw :+1:

**Comment by ineuw** [comment]
Much thanks, I logged it.

ineuw
