### ISSUE TITLE
Esperanto → English: okej translates to "8", while "okay" is what is expected

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [LibreTranslate/LibreTranslate#558]
Hi,

the Esperanto word okej translates in English to "8", while "okay" is expected.

Regards,
Johannes

**Edit:** When the word okej is with lowercase "O" written, sorry, also corrected the output (IDK if it's now (then) even wrong(?)).

**Comment by PJ-Finlay** [comment]
You can submit translation suggestions at LibreTranslate.com by clicking the edit button on the incorrect translation.

![LibreTranslate Edit Translation](https://github.com/LibreTranslate/LibreTranslate/assets/13067016/f2e72091-436b-4bd9-974a-c989661a0c26)
