### ISSUE TITLE
The translations of online demo and local deployment are inconsistent

### ISSUE THREAD

**Issue by Jkanon** [LibreTranslate/LibreTranslate#569]
Hello,

The local server translates the Russaian word "гривен" to incorrect word "griven" in English, while the onlie demo translates it to "the hryvnia" which is correct. I have updated the sofware and models to the latest version. Why is there a difference? Thanks.

![image](https://github.com/LibreTranslate/LibreTranslate/assets/21964895/683bd808-12ec-4be8-8ad8-9a6cdebb4587)
![image](https://github.com/LibreTranslate/LibreTranslate/assets/21964895/8f9fd5e1-ca25-486a-a036-88650064a070)

**Comment by pierotofy** [comment]
https://community.libretranslate.com/t/translation-quality-en-cs-is-different-between-libretranslate-com-and-self-hosted/886/3

(Let's move the conversation to the forum)
