### ISSUE TITLE
Android app: would love it and I can contribute

### ISSUE THREAD

**Issue by diogocsc** [LibreTranslate/LibreTranslate#575]
Would use it often, and would be great to have offline too.
The driver: i wanted to translate online a text bigger than 2000 words from my mobile browser that was just released on Charles Eisenstein newsletter.
An alternative could also be expanding the text limit or translatimg full webpages, just by sharing the url.

Am available to contribute by:

1 - mentoring others to code (have developed one android app in the past). Find me on github: diogocsc

2 - coordinating/project managing the development of such app or web version extension project

3 - testing the app and contributing to documentation

4 - fundraising for this development

5 - sending euros ro those who want ro develop this (even though i kind of need them right now)

6 - donating and fundraising Ğ1, the libre coin, generated per trusted human, based on the number of humans in a trust network

**Comment by argosopentech** [comment]
There already is an open source Android client for LibreTranslate!

The LIbreTranslator app doesn't work offline though; it connects to a LibreTranslate server for translations.

# LibreTranslator
- [Code](https://codeberg.org/BeoCode/LibreTranslator)
- [FDroid](https://f-droid.org/packages/de.beowulf.libretranslater/)
- [Google Play](https://play.google.com/store/apps/details?id=de.beowulf.libretranslater)
