### ISSUE TITLE
Web UI language not changing

### ISSUE THREAD

**Issue by loviuz** [LibreTranslate/LibreTranslate#576]
Hi,

I have installed LibreTranslate with docker image `libretranslate/libretranslate:latest`, but when I change the web ui language with icon on top-right, the language of the web ui does not change. I think this is a bug.

**Comment by jmdaweb** [comment]
Hi,
I have experienced the same issue. The official image doesn't include the compiled translation catalogs. However, when built locally, it includes them, so I understand something is wrong in the GitHub actions workflow.
A workaround for a running container which can be restarted (without the `--rm` option):

1. `docker exec -t -i libretranslate /bin/bash`
2. `cd venv/lib/python3.10/site-packages/`
3. `/app/venv/bin/python /app/scripts/compile_locales.py`
4. Exit and restart the container: `docker restart libretranslate`

@pierotofy could you please take a look and update the official image?
Regards.

**Comment by pierotofy** [comment]
It should be now fixed with the latest image. Thanks for reporting this! 🙏
