### ISSUE TITLE
Setup LibreTranslate on Azure - Issue 

### ISSUE THREAD

**Issue by debanshu-mutt** [LibreTranslate/LibreTranslate#598]
Hello, 
I setup LibreTranslate on my local system - docker build -f docker/Dockerfile [–build-arg with_models=true] -t libretranslate .
Using this and docker image is of 11 GB and working fine.
Same image on Pushing to Azure and running in a Linux OS, for that multiple languages are showing not supported and mostly initial English to other Language is supported not vice versa.

Why is this issue there?
Can someone help out?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
