### ISSUE TITLE
Downloaded models are not compatible with installed version of libretranslate

### ISSUE THREAD

**Issue by deadbeef84** [LibreTranslate/LibreTranslate#600]
I have a docker service based on `libretranslate/libretranslate:v1.3.8`, and it used to work fine. However, if I launch a new instance (or manually update models) some models are no longer compatible:

> 500: Internal Server Error
> 
> Cannot translate text: Unsupported model binary version. This executable supports models with binary version v5 or below, but the model has binary version v6. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)

This was when translating from Swedish to French.

Is there any way to make sure compatible models are downloaded, or do I need to manually cache models to make sure they are not automatically updated to an incompatible version?

**Comment by deadbeef84** [comment]
I think I found a workaround. Setting environment variable `ARGOS_PACKAGE_INDEX` to the argos index to `https://raw.githubusercontent.com/argosopentech/argospm-index/802ad83594e3244e3f908ab0fefc56eef146a5da`, the correct models will be downloaded.

**Comment by pierotofy** [comment]
Awesome you found a workaround; models are not backward compatible, I'd recommend to upgrade if you want to use the latest models. 👍

**Comment by AytoMaximo** [comment]
Hi! I've just installed LibtreTranslate today and have the same error, so I have no idea how can I "upgrade" anything in this situation?
