### ISSUE TITLE
Control panel to manage api Keys in a simpler way

### ISSUE THREAD

**Issue by kaname-png** [LibreTranslate/LibreTranslate#62]
It would be good if they added a control panel to control the access of the api Keys of the api, since doing it by commands is not very practical I think, in my opinion it would be a good idea

What can that control panel have?
1. See the api keys that are currently enabled
2. Disable or enable api key
3. Enable or disable api key system
4. And among other more options for the operation of the website or api

That would be a suggestion that sounds like a good idea to me

**Comment by pierotofy** [comment]
Hey @kaname-png :hand: for sure, it would be a good improvement.

Would you be interested in contributing to this one?

**Comment by kaname-png** [comment]
Hello @pierotofy, sorry for the delay.
I would like to but I don't know Python. :(
