### ISSUE TITLE
Memeory leak in the client on Firefox

### ISSUE THREAD

**Issue by quazar-omega** [LibreTranslate/LibreTranslate#635]
Whenever I start typing into the text box, the memory usage immediately starts ramping up very fast occupying my full 16GB of RAM, also the CPU's temperature went up considerably, past 80°C, it has always led to my PC halting and me having to restart (or wait for the OOM killer to kick in, but I didn't want to wait that long, so I'm not sure).  
Another note: I tried both Auto-detect to English and (selected) Italian to English.

I noticed this issue only on Firefox, trying on Brave it went all smoothly, the resource usage was almost unnoticeable and the translation completed fast.

### Troubleshooting information

Firefox (RPM):
|   |   |
|---|---|
| Version |	126.0 |
| Build ID |	20240520144422 |
| Distribution ID | fedora |

Brave (Flatpak):
|   |   |
|---|---|
| Version | 1.66.118 |
| Chromium | 125.0.6422.147 (Official Build) |

Do let me know if you need more details

**Comment by pierotofy** [comment]
Does this happen if you run in incognito mode?

**Comment by quazar-omega** [comment]
Ah you're right, it doesn't! I guess I have to see if there's an extensions causing this.  
I'm trying now, almost done with it, but I have many extensions and after a bit of back and forth I have to wait for the rate limit to expire now 😆

**Comment by quazar-omega** [comment]
It seems that the extension causing the issue for me is [Textmarker](https://addons.mozilla.org/en-US/firefox/addon/textmarkerpro/) ([source](https://github.com/ufb/Textmarker)), I'll try looking into it more, even though the proect is pretty much unmaintained the extension dev might provide some insight since it seems they're still responsive

**Comment by pierotofy** [comment]
Good find; I'll close this for now as it seems related to an external extension. :pray:

**Comment by quazar-omega** [comment]
Yeah, I don't know what the link with this website even though it has only happened with it, is so I can't comment more on that.  
Trying to debug further, I ascertained that it wasn't that extension alone doing that, neither all my extensions together in a default configuration, so it has to be related both how to they are configured and how they interact with each other in this page.  
Unfortunately I have no idea how to get to the bottom of this by at least finding out which extension starts eating up all the memory, because, as the [documentation](https://support.mozilla.org/en-US/kb/task-manager-tabs-or-extensions-are-slowing-firefox) says, they are all lumped into a single process and even though it suggest to use the Task manager to see details for each (with a link that brings you to the right page, but then redirects you to the source page anyway because the function is not valid anymore in the current version), it isn't possible anymore since they sunsetted `about:performance`, so that's just bad documentation upkeeping.
