### ISSUE TITLE
Translation does not work in multi mode. Won't display HTML tags correctly in the output.

### ISSUE THREAD

**Issue by alexeyrosspage** [LibreTranslate/LibreTranslate#636]
Hello. I run a check through the shell on the PHP. It translates single words normally, but displays HTML tags incorrectly - it loses the quote after the ref. 
For multi-lines, it does not translate the text at all, and does not lose markup characters in HTML.

The tests were for translation from English into Russian:

```
$diffNew = [];
          $diffNew['key0'] = 'Hello <a href="#">This is test 1</a> ready';
          $diffNew['key1'] = 'Hi <a href="javascript:void">This is test 2</a> ready';
          $diffNew['key2'] = 'Good evening <a href="" onclick="checkJs();">This is test 2</a> ready';
//$diffNew = 'Hello <a href="#">This is test for single</a> ready';
          $response = $this->libreTranslate->Translate($diffNew,'en','ru');
```

**Comment by alexeyrosspage** [comment]
I double-checked it again. The problem is only for multi-lines. It works fine for single words and phrases. Sorry.

**Comment by pierotofy** [comment]
Closing since a duplicate discussion was opened here: https://community.libretranslate.com/t/translation-does-not-work-in-multi-mode/1123
