### ISSUE TITLE
Update weblate?

### ISSUE THREAD

**Issue by Blueberryy** [LibreTranslate/LibreTranslate#639]
Please add new language names to Weblate project
![image](https://github.com/LibreTranslate/LibreTranslate/assets/36592509/11988536-9291-48b3-8258-8473fc9a168f)

**Comment by pierotofy** [comment]
You can add new languages directly on Weblate: https://hosted.weblate.org/projects/libretranslate/app/#translations

Just sign-in for an account on Weblate.

**Comment by Blueberryy** [comment]
> You can add new languages directly on Weblate? https://hosted.weblate.org/projects/libretranslate/app/#translations
> 
> Just sign-in for an account on Weblate.

i mean i can't translate them on Weblate into russian because they are not there yet

**Comment by pierotofy** [comment]
You should be able to add a new language in Weblate directly. https://docs.weblate.org/en/latest/devel/translations.html#adding-new-translations

**Comment by Blueberryy** [comment]
> You should be able to add a new language in Weblate directly. https://docs.weblate.org/en/latest/devel/translations.html#adding-new-translations

i'm not an admin on weblate to add new libretranslate's app component strings man

**Comment by salif** [comment]
This issue should be reopened, there are untranslated language names in the UI that are not added to Weblate

**Comment by pierotofy** [comment]
I apologize; when I first read this issue I thought it was a request to add a *new* language, not to update the language *strings*. :pray: my fault.

The strings have now been updated with #657

Thanks for the report.
