### ISSUE TITLE
Local server, translation in Web interface correct, translation via API request bad

### ISSUE THREAD

**Issue by DevServ001** [LibreTranslate/LibreTranslate#647]
Windows 10 LTSC, Python 3.10, no docker, EN to FR

In the localhost:5000 interface, for the EN sentence
  Signal monitoring and fault recognition​
I get the correct translation
  Surveillance des signaux et reconnaissance des défauts

But from an API request from Autohotkey (simplified)
  s := "Signal monitoring and fault recognition​"
  URL := "http://127.0.0.1:5000/translate"
  method := "POST"
  body := '{"q":"' .  s . '","source":"en","target":"fr","format":"text","alternatives":3,"api_key":""}'
  WHR.Open(method, URL, false)
  WHR.SetRequestHeader("Content-Type", "application/json")
  WHR.Send(body)
  WHR.WaitForResponse()
  ResponseRaw := WHR.ResponseText

I get the translation
  Signal surveillance et défaut reconnaissance

Which is incorrect.
Why this difference?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by DevServ001** [comment]
It may be a bug...
