### ISSUE TITLE
Translation from Serbian to English not working

### ISSUE THREAD

**Issue by DusanStijovic** [LibreTranslate/LibreTranslate#656]
When i try to translate from Serbian  to English i got error: 
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
[Example Serbian To English](https://libretranslate.com/?source=sr&target=en&q=Va%C5%BEnost+i+uloga+formalnog+marketin%C5%A1kog+obrazovanja+-+akademske+i+prakti%C4%8Dne+percepcije)

When i try to translate from English to  Serbian everything is okay. 
[Example English To Serbian](https://libretranslate.com/?source=en&target=sr&q=Importance+and+role+of+formal+marketing+education+-+academic+and+practitioner+perceptions)

**Comment by Blueberryy** [comment]
+1, Same with Russian too, when i change language to English it still shows Russian translation.

**Comment by pierotofy** [comment]
Thanks @DusanStijovic for the report :pray:, there was a misconfiguration with the stanza tokenizer. It should now be fixed.

@Blueberryy can you open a new issue with some more details about it?

**Comment by DusanStijovic** [comment]
Can you tell me what to change locally to fix the error?

As I can see, the [argospm-index ](https://github.com/LibreTranslate/LibreTranslate/issues/536)removed the Serbian model from the index because of that error. I installed the model manually and got the same error.

**Comment by pierotofy** [comment]
Make sure the `~/.local/share/argos-translate/packages/sr_en/stanza/sr` directory exists, if not rename the directory with the other name to it.

**Comment by DusanStijovic** [comment]
Thanks. Now it works.

In my setup, I had one more error after renaming the directory.
```
ls ~/.local/share/argos-translate/packages/translate-sr_en-1_0/stanza/ 
resource.json
hy
```
I renamed directory **hy** to **sr** but still got an error.

I saw FileNotFoundError exception in the log files:
` No such file or directory: ~/.local/share/argos-translate/packages/translate-sr_en-1_0/stanza/sr/tokenize/set.pt`
So i renamed 
` ~/.local/share/argos-translate/packages/translate-sr_en-1_0/stanza/sr/tokenize/armtdp.pt`
to 
` ~/.local/share/argos-translate/packages/translate-sr_en-1_0/stanza/sr/tokenize/set.pt`

And then it started working.

**Comment by azivkovi** [comment]
This error still persists in the latest version.

**Comment by azivkovi** [comment]
It appears this is still an issue in the latest version.

> Thanks @DusanStijovic for the report 🙏, there was a misconfiguration with the stanza tokenizer. It should now be fixed.
> 
> @Blueberryy can you open a new issue with some more details about it?

**Comment by PJ-Finlay** [comment]
Related:

https://github.com/LibreTranslate/LibreTranslate/issues/762
