### ISSUE TITLE
Basque translation project needs update in Weblate

### ISSUE THREAD

**Issue by urtzai** [LibreTranslate/LibreTranslate#679]
Comparing with English string quantity [161](https://hosted.weblate.org/projects/libretranslate/app/en/), there are less available in the Basque project: [143](https://hosted.weblate.org/projects/libretranslate/app/eu/)

For example "Albanian", "Chinese (traditional)", "Kabyle" and some other are missing.

I guess the "Basque" string has also to be added :smile: 

Thank you!

**Comment by pierotofy** [comment]
Weblate should have been updated now, thanks!
