### ISSUE TITLE
Few languages missing from Weblate project

### ISSUE THREAD

**Issue by Blueberryy** [LibreTranslate/LibreTranslate#681]
There are 3 new languages which can't be translated for now. Hope they will be added
![image](https://github.com/user-attachments/assets/f36ea5a9-9152-4886-8524-554ba0c7a58c)

**Comment by pierotofy** [comment]
Thanks, this should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/8f33d6e78c45cfec5357090eb27f15dda080d076 :pray:
