### ISSUE TITLE
Basque option needed in the selector

### ISSUE THREAD

**Issue by urtzai** [LibreTranslate/LibreTranslate#691]
I don't know where I can add this option, since the locale is created correctly in the locales folder.

Also messages.pot needs to be updated to include the language name: libretranslate/locales/messages.pot

Thank you

**Comment by urtzai** [comment]
Hi @pierotofy ! I think I managed to solve the issue... Maybe in https://libretranslate.com/ doesn't show up because the language model isn't installed. Once you've downloaded and installed, it appears in the UI (see image below)

![2024-10-17 00-03-00](https://github.com/user-attachments/assets/0b99d8ce-e070-4428-aebe-094ca7d183af)

I would enormously appreciated to update your server so the I can show the potencial of this tool to the Basque community. 

Thank you!

**Comment by pierotofy** [comment]
I've updated the server; Basque is now available from https://eu.libretranslate.com :clinking_glasses:
