### ISSUE TITLE
Memory usage has continued to rise and never went down

### ISSUE THREAD

**Issue by wa008** [LibreTranslate/LibreTranslate#693]
After I hosted the API service, I found the memory utilization is increasing all the time when I send API request, but it never decrease when I stop API request.

So, I must stop and restart the docker container in order to decrease the memory utilization.

<img width="274" alt="image" src="https://github.com/user-attachments/assets/15a192a6-44b8-43ff-88de-95e7b80cd3cb">

I add “docker run -d” parameter when start docker service in the last line of “[run.sh](https://github.com/LibreTranslate/LibreTranslate/blob/main/run.sh)”, is there some wrong?

[same content in forum](https://community.libretranslate.com/t/memory-usage-has-continued-to-rise-and-never-went-down/1548/1)

**Comment by pierotofy** [comment]
Duplicate: https://community.libretranslate.com/t/memory-usage-has-continued-to-rise-and-never-went-down/1548
