### ISSUE TITLE
Community forum verification mail not working

### ISSUE THREAD

**Issue by Hallilogod** [LibreTranslate/LibreTranslate#707]
I am trying to create an account on community.libretranslate.com but the verification email isn't sent.

**Comment by pierotofy** [comment]
We're in the process of fixing it; for some reason spamhaus decided to add our domain in their blacklist, so lots of e-mail providers are putting our e-mails in spam (check there). 🙏

**Comment by Hallilogod** [comment]
No problem, i checked the spam folder but didn't recieve anything, im just using my github account now which is fine too.
