### ISSUE TITLE
[BUG] returns "&" as "&quot;"

### ISSUE THREAD

**Issue by graysuit** [LibreTranslate/LibreTranslate#77]
While seeing a free and open source translator,
I wish to contribute by listing bugs and workaround.

**Noticed Behavior:**
I entered `Entry & Targets:` in **ENGLISH** and it returned `Entrada &quot; Metas:` in **SPANISH**.

**Expected Behavior:**
It should return `Entry & Targets:` in **ENGLISH** as `Entrada & Metas:` in **SPANISH**.

**Workaround:**
Replace `&quot;` with `&` .

**Comment by PJ-Finlay** [comment]
This should be fixed in models >1.1, Spanish is currently still running 1.0.

- https://github.com/argosopentech/argos-translate/issues/39
