### ISSUE TITLE
Bug in translating French via the website

### ISSUE THREAD

**Issue by nsunderland1** [LibreTranslate/LibreTranslate#92]
![image](https://user-images.githubusercontent.com/16548079/119737643-99619300-be4d-11eb-9677-b02f61ac79cd.png)

The input is "Marchons, marchons ! Qu'un sang impur abreuve nos sillons !". The first sentence translates to "Let us march, let us march". The outputted English just spews rough translations of that part over and over again and ignores the second sentence. Weirdly, if you insert a newline between the two sentences, the problem is solved and you get a somewhat accurate translation (although as far as I can tell "abrate" is not a word).

![image](https://user-images.githubusercontent.com/16548079/119738159-44724c80-be4e-11eb-9f3a-9b1bf78eed8a.png)

**Comment by PJ-Finlay** [comment]
Since this was fixed by inserting a new line I'm guessing this is an issue with the Stanza, the sentence boundary detection system. To see debugging output you can run with:
```
export DEBUG=1
```
